### ISSUE TITLE
Figure out why Vibration.vibrate() doesn't work in some instances for iOS

### ISSUE THREAD

**Issue by moaazsidat** [moaazsidat/react-native-qrcode-scanner#1]
The QR code scanner component has it so that a vibrate event is sent upon successfully reading a code. However, calling `Vibration.vibrate()` doesn't seem to work. Will have to investigate further.

**Comment by robert589** [comment]
We experience this also, any idea?

**Comment by renatobenks** [comment]
can you describe better @robert589, what are you actually experiencing? I would be happy to help you with this if you're still facing it!

but it's not clear to me yet the unexpected behavior here, as it's an older issue that seems to be fixed (not sure) as on reading correctly a QR code the auto vibration in iOS is working.

**Comment by renatobenks** [comment]
I'll be closing this because it seems to be already fixed for a long time ago and it doesn't sound still to be a problem at all
