### ISSUE TITLE
Camera Error

### ISSUE THREAD

**Issue by kamalkech** [moaazsidat/react-native-qrcode-scanner#102]
![1](https://user-images.githubusercontent.com/1313428/39957730-8ee348ca-55ef-11e8-934d-4b89866955fc.png)

any idea plz ?

**Comment by AliRadmanesh** [comment]
I have this error too. about a month ago I used this package with react-native 0.54 and everything was good. but now I have this error and I can't find solution for it :/

**Comment by moaazsidat** [comment]
Please note that React Native Camera underwent major changes, make sure after upgrading to the latest version of react-native-qrcode-scanner, you've followed the migration guide (from React Native Camera) : https://github.com/moaazsidat/react-native-qrcode-scanner/blob/master/migration.md

**Comment by AliRadmanesh** [comment]
I found the solution here: (can't find the link. it's a capture of it :)

![react-native-camera error solution](https://user-images.githubusercontent.com/23115511/40440508-87ceaac4-5ed3-11e8-9dd8-9b90da0ee983.jpg)
