### ISSUE TITLE
Can't find variable : QRCodeScanner (In android)

### ISSUE THREAD

**Issue by himaanshi** [moaazsidat/react-native-qrcode-scanner#106]
I am using 
 "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-camera": "^1.1.4",
    "react-native-qrcode-scanner": "^1.0.1"

In ios app is working but in android  app is showing error 

  ReferenceError: Can't find variable: QRCodeScanner
    This error is located at:
        in t
        in RCTView
        in RCTView
        in t_

Please help .

**Comment by amalmohann** [comment]
> I am using "react": "16.3.1", "react-native": "0.55.4", "react-native-camera": "^1.1.4", "react-native-qrcode-scanner": "^1.0.1"
> 
> In ios app is working but in android app is showing error
> 
> ReferenceError: Can't find variable: QRCodeScanner This error is located at: in t in RCTView in RCTView in t_
> 
> Please help .

have you fixed this?
