### ISSUE TITLE
Cannot read property 'Aspect' of undefined

### ISSUE THREAD

**Issue by ParveenChhillar** [moaazsidat/react-native-qrcode-scanner#109]
import React, { Component } from 'react';

import {
  AppRegistry,
  StyleSheet,
  Text,
  TouchableOpacity,
  Linking,
} from 'react-native';

import QRCodeScanner from 'react-native-qrcode-scanner';

class ScanScreen extends Component {
  onSuccess(e) {
    Linking
      .openURL(e.data)
      .catch(err => console.error('An error occured', err));
  }

  render() {
    return (
      <QRCodeScanner
        onRead={this.onSuccess.bind(this)}
        topContent={
          <Text style={styles.centerText}>
            Go to <Text style={styles.textBold}>wikipedia.org/wiki/QR_code</Text> on your computer and scan the QR code.
          </Text>
        }
        bottomContent={
          <TouchableOpacity style={styles.buttonTouchable}>
            <Text style={styles.buttonText}>OK. Got it!</Text>
          </TouchableOpacity>
        }
      />
    );
  }
}

const styles = StyleSheet.create({
  centerText: {
    flex: 1,
    fontSize: 18,
    padding: 32,
    color: '#777',
  },
  textBold: {
    fontWeight: '500',
    color: '#000',
  },
  buttonText: {
    fontSize: 21,
    color: 'rgb(0,122,255)',
  },
  buttonTouchable: {
    padding: 16,
  },
});

AppRegistry.registerComponent('default', () => ScanScreen);

**Comment by alexbadm** [comment]
The same problem.
I did not insert QRCodeScanner component to JSX but just import them and it throws the error:
`undefined is not an object (evaluating 'CameraManager.Aspect')`

Android emulator and Android device.

**Comment by zMathieu** [comment]
Same problem when trying the sample code in README (I'm using expo with and Android 8.1 device to run the application), I got this error :
`undefined is not an object (evaluating 'CameraManager.Aspect')`

Can anyone help us to solve this ? Thanks !

**Comment by abdollahpour** [comment]
Same problem, I'm just trying to run the sample on README

**Comment by MSharifi78** [comment]
I had the same problem on Android, so I bundle it again and run it with `react-native run-android`
then I face to this issue `Could not find method compileOnly()` that is related to [https://github.com/react-native-community/react-native-camera/issues/1490](url)
finally, it's fix :)
sorry for my terrible English

**Comment by netProgrammer** [comment]
Same problem when trying the sample code in README (Android 8.1)

**Comment by axschlamp** [comment]
Manually linking the react-native-camera lib resolved this issue for me. @ParveenChhillar Take a look under Manual Install iOS step two through five.

https://github.com/react-native-community/react-native-camera#ios

**Comment by moaazsidat** [comment]
yep, make sure to follow installation instructions around linking carefully. going to mark this as resolved, please feel free to reopen if still an issue.
