### ISSUE TITLE
Qr Scanner in TabNavigation

### ISSUE THREAD

**Issue by alz10** [moaazsidat/react-native-qrcode-scanner#116]
Hello, how can i open the camera again after i click on the other navigationTab. It became black after i go back to QrScanner Tab. Im using `react-navigation` v2

![untitled-1](https://user-images.githubusercontent.com/38030623/42125143-a75fb292-7c25-11e8-9556-e91b942a292e.png)

**Comment by SeamusY** [comment]
You may want to consider ComponentDidmount and WillUnmount, see if that changes anything.

**Comment by ajiehatajie** [comment]
same here in tabs navigations if i back to menu tabs camera is blank screen

**Comment by Albert0405** [comment]
@ajiehatajie  i fix it, https://github.com/react-native-community/react-native-camera/issues/1671#event-1709976014

**Comment by ajiehatajie** [comment]
@Albert0405 can i see your code for fix it

**Comment by Albert0405** [comment]
`import { withNavigationFocus } from "react-navigation";`

```
renderCamera() {
    const isFocused = this.props.navigation.isFocused();
    if (!isFocused) {
      return null;
    } else if (isFocused) {
      return (
        <QRCodeScanner />
}
```

```
render() {
    return (
      <View style={{ flex: 1 }}>
        {this.renderCamera()}
      </View>
}
```

**Comment by ajiehatajie** [comment]
@Albert0405 thank you sir is work fine.

**Comment by moaazsidat** [comment]
@Albert0405 thanks for resolving this, do you think this is a good candidate to add in the examples?

**Comment by Albert0405** [comment]
@moaazsidat I think so, this is the only way i see to fix this problem because each tab in according to react-navigation devs, they dont re-render themselves when switching tabs.

**Comment by danhnguyeen** [comment]
Hope it help
```

import React, { Component } from 'react';
import {
  View
} from 'react-native';
import QRCodeScanner from 'react-native-qrcode-scanner';

class QRCode extends Component {
  state = {
    isRender: true
  }
  componentDidMount() {
    this.props.navigation.addListener('willFocus', (route) => {
      this.setState({ isRender: true })
    });
    this.props.navigation.addListener('willBlur', (route) => {
      this.setState({ isRender: false })
    });
  }

  render() {
    return (
      <View style={{flex: 1}}>
        { this.state.isRender &&
          <QRCodeScanner />
        }
      </View>
    );
  }
}
export default QRCode;

```

**Comment by superp** [comment]
Neither of these methods has helped for me. 
Still seeing a black screen after changing tabs.

P.S. @Albert0405 How did you implement blurred style for the camera? And white corners style for a marker?

**Comment by Albert0405** [comment]
check this one, i shared my code there
#115

**Comment by anibaghi** [comment]
@Albert0405 sorry my question actually didn't relate to your post. But how did you create that custom marker? Can you please share the code?

**Comment by superp** [comment]
> @Albert0405 sorry my question actually didn't relate to your post. But how did you create that custom marker? Can you please share the code?

Here is an answer:

> check this one, i shared my code there #115
> 
> you need to re-render the component to prevent the black screen. I haven't tried this solution yet because i dont use this library anymore but everytime the tabs is shown on the screen, use this `this.forceUpdate();`

**Comment by ThaJay** [comment]
@danhnguyeen Thank you that solution works for me. just some notes:
- I think `shouldRender` is a better name for the prop
- In the render function I rather use the pattern: `if (condition) return <Component />; else return null`
- remember to remove the listeners according to the documentation:
```
  componentDidMount () {
    this.removeWillBlurListener = this.props.navigation.addListener(
      'willBlur', () => {this.setState({shouldRender:false})}
    )
  }

  componentWillUnmount () {
    this.removeWillBlurListener()
  }
```
https://reactnavigation.org/docs/en/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle

**Comment by renatobenks** [comment]
I'll be closing this issue as this is not a problem at all but limitation by design between `react-native-camera` and routers navigation libraries, like `react-navigation`

but I agree as well that we should have an example, at least, about how to solve this problem as it was been well-appointed by you guys in the suggestions above, so I've created this following issue to add this example, so hopefully would be nice if someone of you guys could contribute to as you guys did above.
