### ISSUE TITLE
Feature Request: Camera Timeout

### ISSUE THREAD

**Issue by giorgosioak** [moaazsidat/react-native-qrcode-scanner#123]
Could you implement a camera timeout with a message "Tap to activate camera".

Could be:
```
<QRCodeScanner
...
cameraTimeout={20} // blank after 20 seconds
/>
```

**Comment by moaazsidat** [comment]
Please see: https://github.com/moaazsidat/react-native-qrcode-scanner#reactivatetimeout for basic usage. 

Accepting pull requests implementing the proposed functionality.

**Comment by gie3d** [comment]
I would like to work on this and will try to submit PR soon.

**Comment by renatobenks** [comment]
I was wondering about this issue and I just thought about if this proposed text message to timeout shouldn't be more out of the box as an API? I mean, why the text "Tap to activate camera" it's hardcoded?

**Comment by renatobenks** [comment]
@moaazsidat can you take a look at #132? it seems to have in progress working by @gie3d to get it done but I don't know if it's properly done well as expected. what do you think?
