### ISSUE TITLE
Barcode doesn't scan on front camera

### ISSUE THREAD

**Issue by trubi** [moaazsidat/react-native-qrcode-scanner#128]
Hello,

when trying to scan barcode from front camera, it doesn't work. Barcode scanning seems to work only on back camera. QR codes are scanning fine on both cameras.

```
<QRCodeScanner
                    onRead={this.onRead}
                    cameraStyle={{
                        flex: 1,
                        width: Dimensions.get("window").width - 345,
                    }}
                    topViewStyle={{ flex: 0, height: 0, width: 0 }}
                    bottomViewStyle={{ flex: 0, height: 0, width: 0 }}
                    cameraType={this.props.cameraType} // "front" | "back"
                    reactivate={true}
                    fadeIn={false}
                    reactivateTimeout={2000}
                    showMarker={true} />
```

Versions:

"react-native-camera": "1.2.0",
"react-native-qrcode-scanner": "1.0.1",
"react-native": "0.51.0",
"react": "16.2.0",
iOS version tried: 11.4.1, but happens on multiple iPads here in office with different versions

Any ideas? Could it caused by low quality front camera (iPad Air 2) or horizontally flipped scanning on front camera?

**Comment by avjabalpur** [comment]
+1

**Comment by avjabalpur** [comment]
Hi, 

Please help on this

**Comment by renatobenks** [comment]
it seems to be related with a bug on `react-native-camera` side, did you check for this same problem over there @avjabalpur?

**Comment by renatobenks** [comment]
well, I did find in advance an issue over there telling that is not possible to be able to, for now. It's Google MLKit limitation, as you check here https://github.com/react-native-community/react-native-camera/issues/2363#issuecomment-509765993

So, I'll be closing this one, and if you want  to work in any workaround to solve this problem, please, make a suggestion in `react-native-camera` instead
