### ISSUE TITLE
Scan code which contains embed images or logo

### ISSUE THREAD

**Issue by hoanghaihuy** [moaazsidat/react-native-qrcode-scanner#130]
How can I scan a code which has a image inside of the QR code?

For example:
![image](https://user-images.githubusercontent.com/23524337/44573831-e81c0300-a7b1-11e8-8514-c8e5c05c2724.png)

**Comment by Transfusion** [comment]
That QR code scans fine for me on a Huawei RNE-L22 (nova 2i) running 7.0 and a Xiaomi Mi 6 running 8.0.0, added `"react-native-camera": "^1.2.0"` to dependencies with RN 0.55.4. 

`{"bounds":[{"y":"682.5","x":"838.5"},{"y":"690.0","x":"465.0"},{"y":"291.0","x":"469.5"},{"y":"364.0","x":"796.75"}],"type":"QR_CODE","data":"http://1qr.fr/whb0","target":864}"`

**Comment by moaazsidat** [comment]
@hoanghaihuy is this still an issue?
