### ISSUE TITLE
Change Height And Width not work .

### ISSUE THREAD

**Issue by onusgit** [moaazsidat/react-native-qrcode-scanner#134]
I have only small size of scanner camera . but I am not able to change this .

**Comment by pkyeck** [comment]
I also have the problem that on Android (v8 / Pixel 1) the camera can't be square anymore. I didn't change anything and suddenly it's rectangular and not square anymore. Even setting width + height to e.g. 100 won't result in a square. Anyone else having this problem?

BTW, iOS works as expected

**Comment by kevintran1402** [comment]
i have a specified width + height for camera scanner but when active & dragging camera from outside of my laptop display screen but it’s still can read qr code even qr code is out side of camera and scan area..it’s really weird!!

camera scan area: 
height: 30% of dimension.height
width: 25% of dimension.width

**I think the scan area always full instead limited by my specified height.
any help or solution for my case?

**Comment by pkyeck** [comment]
@onusgit why did you close this? seems like a lot of people are having issues with resizing the camera-component

**Comment by hecontreraso** [comment]
Same error here

**Comment by tannera** [comment]
This library is now broken on Android with react-native-camera": "^1.3.0? 

The Camera size overlaps the TopContent and BottomContent.

**Comment by matoxxx** [comment]
I'm having same problems with package `"react-native-camera": "^1.3.0"`.

Any solution?

**Comment by anil-kumar-singh** [comment]
I am having same problem, any solution please?

**Comment by anil-kumar-singh** [comment]
I have given some style to top and bottom view to manage this

```
topViewStyle={{backgroundColor:'#fff', zIndex: 1000}}
bottomViewStyle={{backgroundColor:'#fff'}}
```

**Comment by MRDjeko** [comment]
> I find this error solution

How did you solve it?

**Comment by ducbka02** [comment]
Just add props "ratio='1:1'" to cameraProps

**Comment by MRDjeko** [comment]
> Just add props "ratio='1:1'" to cameraProps

Thanks! It kinda works, but I end up with distorted preview. It basically scales 4:3 feed to fit into 1:1 container, so the feed ends up stretched. In older versions (well, in my case upgrading to a newer version of react native broke it) it worked fine, without stretching the preview.

**Comment by cyannuro** [comment]
> Just add props "ratio='1:1'" to cameraProps

it works, using cameraProps={{ ratio:'1:1' }} ;)

**Comment by vivekkritikal** [comment]
> Just add props "ratio='1:1'" to cameraProps

Not working for Version 8.1.0 ... Camera Blackout Issue

**Comment by mdarifulislamroni521** [comment]
> Just add props "ratio='1:1'" to cameraProps
thanks bro its working good

<QRCodeScanner
          onRead={this.onSuccess}
          flashMode={RNCamera.Constants.FlashMode.off}
          cameraProps={{ ratio: '1:1' }}
        />
