### ISSUE TITLE
disable vibration

### ISSUE THREAD

**Issue by rogerkerse** [moaazsidat/react-native-qrcode-scanner#140]
Is it possible to disable vibration? I have "reactivate" on, because I want it to constantly scan, but it is very annoying when it constantly buzzes when pointed at the same code

**Comment by suretarget** [comment]
`vibrate={false}`

**Comment by moaazsidat** [comment]
marking this as resolved, please reopen if this is still outstanding

**Comment by renanmav** [comment]
This should be added to the README.md
