### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by vedovato** [moaazsidat/react-native-qrcode-scanner#146]
I'd like to fix #79. How can i contribute?
I'm not being able to modify the package code.

Everytime i save the index.js file inside my node_modules/react-native-qrcode-scanner/, my modifications won't load up. Honestly i could only add console.warns in it and even if i change any string, it won't upgrade on project.

Also, tried to reference in package.json as cloned module from local filesystem which didn't work.
Please help :)

**Comment by moaazsidat** [comment]
@vedovato thanks for reaching out. 

To contribute and test your changes. 
1. Clone https://github.com/moaazsidat/react-native-qrcode-scanner
2. Make changes
3.

**Comment by moaazsidat** [comment]
I've also just added a contribution guide: https://github.com/moaazsidat/react-native-qrcode-scanner/blob/master/CONTRIBUTION.md
