### ISSUE TITLE
Suggest to have a props for camera container.

### ISSUE THREAD

**Issue by resting** [moaazsidat/react-native-qrcode-scanner#147]
Trying to style camera with `flex:5` and the bottomView with `flex:1` but there's no way to do it now.
We can have a `cameraContainer` props for that purpose.

**Comment by moaazsidat** [comment]
Sure thing, accepting PRs implementing this.

**Comment by renatobenks** [comment]
hey @resting the `containerStyle` prop wouldn't work to you in this case?
