### ISSUE TITLE
How to reactivate QRCodeScanner after navigating back to screen/component containing it?

### ISSUE THREAD

**Issue by gititon** [moaazsidat/react-native-qrcode-scanner#15]
Hi,

Thank you for making this available to the community! I'm using the [React Navigation](https://reactnavigation.org/)  library to navigate to another screen upon a successful QR code scan. 

I have reactivate set to false (the default) so that the app isn't constantly vibrating/trying to scan another QR code while I'm on another "screen" of the app. However, when I navigate back to my screen/component that contains the QRCodeScanner component, render() must not be called again because I cannot scan another QR code.

Can you please tell me how I can get QRCodeScanner to scan again when navigating back to it? Thank you!

**Comment by moaazsidat** [comment]
Hey @gititon, thanks for the question. I think this is a pretty common question with regards to the usage of the library, however, I'm currently thinking about it in terms of what would be the most reasonable way to implement this within the library. Going to spend some time over the weekend trying to sort this out, thanks for your patience!

**Comment by parkerdan** [comment]
Just put it in a `Modal` and access with a `Touchable`

**Comment by djavier** [comment]
Hi @parkerdan could you elaborate a little bit more?

**Comment by madki** [comment]
@moaazsidat You can reactivate it by setting getting a reference to the component and using `scanner._setScanning(false)`. A better API would be to add a method called `reactivate()` to `QRCodeScanner`.

Here's a complete example:
```jsx
render() {
    let scanner;

    const startScan = () => {
      if (scanner) {
        scanner._setScanning(false);
      }
    };

    return (
      <QRCodeScanner
        ref={(camera) => scanner = camera}
        onRead={this.onSuccess.bind(this)}
        topContent={topContent}
        bottomContent={(<Button title="Reactivate" onPress={() => startScan()} />)}
        style={{flex: 1}}
      />
    );
  }
```

**Comment by lodi-g** [comment]
Thanks @madki 
Worked well for me.

**Comment by moaazsidat** [comment]
@madki thanks for the suggestion, would you be able to submit a PR with the suggested changes? Thanks!

**Comment by moaazsidat** [comment]
Added in [0.0.20](https://www.npmjs.com/package/react-native-qrcode-scanner), 
docs: https://github.com/moaazsidat/react-native-qrcode-scanner#reactivate
