### ISSUE TITLE
scanning angle about barcode scanning 

### ISSUE THREAD

**Issue by BadMaker** [moaazsidat/react-native-qrcode-scanner#150]
it's difficult to read barcode while scanning ,you need make a special angle to scan

### What's happening?

it's difficult to read barcode while scanning ,you need make a special angle to scan

**Comment by BadMaker** [comment]
似乎需要在特定的角度内才能扫描到，该角度与条码所在平面几乎平行，并且可调动范围非常窄

**Comment by moaazsidat** [comment]
I would consider this a problem of the underlying camera API.

**Comment by BadMaker** [comment]
> I would consider this a problem of the underlying camera API.
well,Thank you sir,Thank you very much.
