### ISSUE TITLE
I can't change the height. It doesn't matter though I set height 100(for example)

### ISSUE THREAD

**Issue by CFdong** [moaazsidat/react-native-qrcode-scanner#154]
It happens in android. IOS works well.

**Comment by trialsNow** [comment]
Same for me as well.. I tried overriding camerastyle as well, doesnt work in android. Works perfectly in iOS

**Comment by howieyoung** [comment]
Got the same issue and solved it successfully
I've explained it at #173, feel free to check it and hopefully it's helpful for your case.

**Comment by CFdong** [comment]
> Got the same issue and solved it successfully
> I've explained it at #173, feel free to check it and hopefully it's helpful for your case.

thank you
