### ISSUE TITLE
Getting Camera not Authorized Message

### ISSUE THREAD

**Issue by hamrosh** [moaazsidat/react-native-qrcode-scanner#160]
I am getting allow camera permission message, after allowing it is just showing "Camera not authorized " message, can you help me resolve this?

**Comment by cstranex** [comment]
Set the camera props: `cameraProps={{captureAudio: false}} `

**Comment by hamrosh** [comment]
> Set the camera props: `cameraProps={{captureAudio: false}} `

export default class App extends Component {
  render() {
    return <QRScanner cameraProps={{ captureAudio: false }} />;
  }
}

still showing the same message

**Comment by GaneshSaiKumar** [comment]
yes, even i'm getting the same issue

**Comment by hamrosh** [comment]
> Set the camera props: `cameraProps={{captureAudio: false}} `

Thank you very much for your solution,, now i can see the camera and it is scanning the qr codes and i am getting the cotent from qr code. we have to user reactivate() function to enable scanning again ??

**Comment by GaneshSaiKumar** [comment]
working fine TQ

**Comment by GaneshSaiKumar** [comment]
but blank cam is opeing not able to see any think, .
@hamrosh  
can you list your dependencies
tq in advance

**Comment by beyns** [comment]
<QRCodeScanner
        onRead={this.onSuccess.bind(this)}
        cameraProps={{ captureAudio: false }}
        topContent={.........

i set the cameraProps = captureAudio:false but 'camera not found' still showing up

**Comment by krisnailafat** [comment]
im using android version 5.1
still got this message Camera not Authorized

I tried this still dont work

> cameraProps={{captureAudio: false}}

and this dont work either

> let checkAndroidPermission = true
    if (Platform.OS === 'android' && Platform.Version < 23) {
      checkAndroidPermission = false
    }

    <QRCodeScanner
          ...
          checkAndroid6Permissions={checkAndroidPermission}
          ...
     />

**Comment by rgfretes** [comment]
DId you find any way to make it work @krisnailafat ? I am still experiencing it and I cannot upgrade the version with this problem.

**Comment by frangeris** [comment]
@rgfretes Update `react-native-camera` fixed on [v1.10.2](https://github.com/react-native-community/react-native-camera/releases/tag/v1.10.2)

**Comment by vinaygoyal20** [comment]
I was able to fix it by
installing react-native-permissions
and in pod file
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

**Comment by wahajzafarkhan** [comment]
<QRCodeScanner
        cameraProps={{ captureAudio: false }}
        onRead={onSuccess}
        flashMode={RNCamera.Constants.FlashMode.torch}
        topContent={
          <Text style={styles.centerText}>
            Scan{' '}
            <Text style={styles.textBold}>BarCode</Text> From Here
          </Text>
        }
        bottomContent={
          <TouchableOpacity style={styles.buttonTouchable}>
            <Text style={styles.buttonText}>OK. Got it!</Text>
          </TouchableOpacity>
        }
      />

its not working 
![WhatsApp Image 2021-09-13 at 5 17 54 AM](https://user-images.githubusercontent.com/90195462/133083262-ad0aa997-f996-4862-b870-af92f20a21ce.jpeg)

**Comment by wahajzafarkhan** [comment]
even my app doesnt install after installing the react native camera package

**Comment by renatobenks** [comment]
That problem is entirely, and only, related to setting things up. Therefore, if you're facing something like this, is probably something misconfigured in your app's permission with react-native-permissions. So, I encourage you to take a better look again in the README, including the documentation from that package, where it'll be well detailed for you. All the workarounds shared above works only because you didn't set the configurations right, once that package is only a small top-layer abstraction, and we're just checking on our side if you have the right permissions or not.

Either way, I'm closing this issue.
