### ISSUE TITLE
Black screen after scanning a qr code

### ISSUE THREAD

**Issue by GaneshSaiKumar** [moaazsidat/react-native-qrcode-scanner#161]
@moaazsidat  @mamodom @mjgallag 
### What's happening?
after scanning a qr code successfully, I'm redirecting to other screen.
when i come back to qr code scanning screen, cam is blacked out.

### How can it be reproduced?
add a qr code scanner screen and other screen in a tab nav bar

### Build details?
version: react-native-qrcode-scanner - 1.1.2
android: 7.0
react-native: 57

**Comment by GaneshSaiKumar** [comment]
I think it is issue from RNcamera itself!

**Comment by GaneshSaiKumar** [comment]
https://github.com/react-native-community/react-native-camera/issues/1686#issuecomment-427839839

` componentDidMount() {
    const { navigation } = this.props;
    navigation.addListener('willFocus', () =>
      this.setState({ focusedScreen: true })
    );
    navigation.addListener('willBlur', () =>
      this.setState({ focusedScreen: false })
    );
  }

  render() {
    const { hasCameraPermission, focusedScreen } = this.state;
    if (hasCameraPermission === null) {
      return <View />;
    } else if (hasCameraPermission === false) {
      return <Text>No access to camera</Text>;
    } else if (focusedScreen){
      return (this.cameraView());
    } else {
      return <View />;
    }
  }`

this solved my issue.

still the appearance of camera is flicker, using animated view in react-native-qrcode-scanner

**Comment by GaneshSaiKumar** [comment]
initial screen itself is freezing with blank black screen instead of camera interface
@moaazsidat @matthewconstantine

**Comment by paakcmd** [comment]
> initial screen itself is freezing with blank black screen instead of camera interface
> @moaazsidat @matthewconstantine
> is there a way out?

I think your camera component never remount after the first usage. The easiest way to fix is to give the component the unique value every time you rout to the component. 
Actions.scanner({unique: Date.now() })

**Comment by j0nd0n7** [comment]
This issue is from RNCamera, and its solution is documented here:
https://github.com/react-native-community/react-native-camera/blob/master/docs/react-navigation.md

The solution is for react-navigation however a similar approach could be implemented with other navigation packages (like react-native-navigation using componentDidAppear and componentDidDisappear.

**Comment by AzranAzwer** [comment]
Thank you @j0nd0n7 for the link...

`import { useIsFocused } from '@react-navigation/core';

export const Component = () => {
  const isFocused = useIsFocused();

  // ...

  if (hasCameraPermission === false) {
    return <Text>No access to camera</Text>;
  } else if (hasCameraPermission !== null && isFocused) {
    return <CameraView />;
  } else {
    return null;
  }
}
`
