### ISSUE TITLE
onPress being called when QRCode is scanned

### ISSUE THREAD

**Issue by Caleb-Tan** [moaazsidat/react-native-qrcode-scanner#167]
I have an issue where I have a touchable opacity in my bottomContent, and I have a method that is being invoked when I press a button. I only want this method to be invoked when I press the button, but it is being called every time I scan a qrcode, as well as when the app is first rendered.

In bottomContent: 
```
              <TouchableOpacity onPress={this._uploadData()} style={styles.UploadButton}>
                <View style={styles.Center}>
                  <Text style={[styles.Font ,{color: 'white'}]}>Upload Data</Text>
                </View>
              </TouchableOpacity>
```
_uploadData() is the method being called constantly. The touchable opacity is the only place where it is referenced.

**Comment by vvteixeira** [comment]
Not sure if you figured it out yet, but you're calling the function instead of only making a reference. Try to remove the "()" from the "this._uploadData" like this:
```
<TouchableOpacity onPress={this._uploadData} style={styles.UploadButton}>
   ...
</TouchableOpacity>
```
