### ISSUE TITLE
Disable scanning barcode types other than QR code

### ISSUE THREAD

**Issue by nithyan** [moaazsidat/react-native-qrcode-scanner#172]
### What's happening?
Is there a way to disable scanning bar code types other than QR_CODE. Though there is a provision in RNCamera, there is no property exposed from the library to take in the restricted barcode types.
For eg: 
```<Camera barCodeTypes={[RNCamera.Constants.BarCodeType.qr]} /> ```

**Comment by j0nd0n7** [comment]
Use cameraProps to set the props for RNCamera
