### ISSUE TITLE
[Android] Should add a props to fix the issue on failing to change camera size

### ISSUE THREAD

**Issue by howieyoung** [moaazsidat/react-native-qrcode-scanner#173]
Like many other issues mentioned, the size of camera is unable to be changed in some SDK version (not sure which versions are them, it worked fine on 26 but broken on 28 in my case).

After I added a ratio manually like below I can resize the camera into square again
```
<Camera
    ratio={"1:1"}  //add this line manually to avoid the camera being resized into 4:3 by default
    style={[styles.camera, this.props.cameraStyle]} 
    onBarCodeRead={this._handleBarCodeRead.bind(this)}
    type={this.props.cameraType}
>
```

So perhaps it would be helpful to have a [props.cameraRatio] in the future to deal with the resizing of camera. Just like:

```
<Camera
    ratio={this.props.cameraRatio} 
    style={[styles.camera, this.props.cameraStyle]} 
    onBarCodeRead={this._handleBarCodeRead.bind(this)}
    type={this.props.cameraType}
>
```

---------------------

P.S I really appreciate you guys made this package, our team use it in our project(called [tico](https://tico.app)), it's really helpful and easy to be implemented. Good job and thank you :)

**Comment by jtarini** [comment]
@howieyoung I faced the same issue and fixed just adding `cameraProps={{ratio: "1:1"}}`

**Comment by legend1250** [comment]
The same with me and solved by adding `cameraProps={{ratio: "1:1"}}`. Have anyone make this pull request?

**Comment by howieyoung** [comment]
Set camerasProps={{ “1:1” }}  also works on my test. Thanks for the supplements 👍

**Comment by moaazsidat** [comment]
Marking this as resolved, please feel free to open a PR if you think that would improve the experience of using the package, thanks for using this library!

**Comment by vivekkritikal** [comment]
> @howieyoung I faced the same issue and fixed just adding `cameraProps={{ratio: "1:1"}}`

Camera Blackout issue in version 8.1.0 .. For rest version working fine

**Comment by SL-A-SH** [comment]
Doesn't work. I am using sdk version 28

**Comment by Valentinishe** [comment]
https://github.com/moaazsidat/react-native-qrcode-scanner/issues/182 
`cameraStyle={{overflow: 'hidden'}}` - it helped me

**Comment by omair2010** [comment]
**its work as well like that** 
```jsx
import React from 'react';
import { StyleSheet } from 'react-native';
import QRCodeScanner from 'react-native-qrcode-scanner';

import TopNavigation from '../../components/TopNavigation';
import { Layout } from '../../components/Layout';

import { theme } from '../../theme';

const styles = StyleSheet.create({
  markerStyle: {
    borderColor: theme['color-brandSecondary-default'],
    borderRadius: 20,
    width: 150,
    height: 150,
  },
  cameraStyle: {
    backgroundColor: 'red',
    height: '100%',
    width: '100%',
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: theme['color-brandSecondary-default'],
  },
  containerStyle: {
    justifyContent: 'center',
    alignItems: 'center',
    margin: 20,
  },
});
const { markerStyle, cameraStyle, containerStyle } = styles;
const QrCode = ({ navigation }) => {
  return (
    <Layout>
      <TopNavigation withLogo withMenu navigation={navigation} />
      <QRCodeScanner
        cameraProps={{ ratio: '1:1' }}
        // onRead={handleQrCodeReaded}
        containerStyle={containerStyle}
        cameraStyle={cameraStyle}
        flashMode={2}
        showMarker
        markerStyle={markerStyle}
        reactivate
        reactivateTimeout={3000}
      />
    </Layout>
  );
};

export default QrCode;

```
you can remove the margin in containerStyle if u dont need it
