### ISSUE TITLE
Need help to reactivate the qr scanner

### ISSUE THREAD

**Issue by YisusMB** [moaazsidat/react-native-qrcode-scanner#181]
### What's happening?
Actually this is my code but when i try to call reactivate this dosnt work with this message "_this.scanner.reactivate is not a function"

`<QRscanner
      ref={(node) => this.scanner = node}
      reactivate={true}
      onRead={this.onRead}
      // renderTopView={this.topView}
      renderBottomView={
           <TouchableOpacity 
            style={{marginTop: 15}}
            onPress={ this.scanner.reactivate()}>
            <Text>Reactivate</Text>
          </TouchableOpacity>
}
      rectHeight={200}
      bottomViewStyle={{ height: 200}}
      flashMode={this.state.flashMode}
      zoom={this.state.zoom}
      finderY={50}/>`
### Build details?

Android 9.0
iOS 12.2

Can anyone help me pls?  :C

**Comment by bova80** [comment]
if you already have reactivate={true} set in your properties then calling it won't do much cause as soon as it scans it reactivating.   this.scanner.reactivate() works for me in this situation: 

onSuccess = (e) => {
    Alert.alert('Successful Scan', 'Navigate to: '+e.data, [
      {
        text: 'Cancel',
        onPress: () => this.scanner.reactivate(),
        style: 'cancel',
      },
      {text: 'OK', onPress: () => this.successfullScan(e.data)},
    ],
    {cancelable: false},);
    
  }

**Comment by YisusMB** [comment]
> if you already have reactivate={true} set in your properties then calling it won't do much cause as soon as it scans it reactivates. If you want a button to do it then don't set that prop. this.scanner.reactivate() works for me in this situation:
> 
> onSuccess = (e) => {
> Alert.alert('Successful Scan', 'Navigate to: '+e.data, [
> {
> text: 'Cancel',
> onPress: () => this.scanner.reactivate(),
> style: 'cancel',
> },
> {text: 'OK', onPress: () => this.successfullScan(e.data)},
> ],
> {cancelable: false},);
> 
> }

@bova80 i check with your code and still have "_this.scanner.reactivate is not a function" :/ and i dont know why my version is     "react-native-qr-scanner": "^1.3.2",

**Comment by YisusMB** [comment]
UPDATE--
set the prop 'isRepeatScan={true}' make this functionally but this one no have timeout, actually, the camera scans an infinite loop of times, this until you remove the QR from where the camera can read it anyone have other solution for this??

**Comment by YisusMB** [comment]
Just forget this issue, my bad i install other package, i migrate to this and all works sorry for my dumb issue

**Comment by shantang96** [comment]
Hey YisusMB, I'm getting the same issue. It says 'undefined is not an object (evaluating _this2.scanner.reactivate). How did you fix this? I tried setting 'isRepeatScan={true}, but that didn't fix it.

**Comment by YisusMB** [comment]
@shantang96 pls show me your code and your react native, react-native-cli & react-native-qrcode-scanner version it would be helpful

**Comment by shantang96** [comment]
@YisusMB Hey! I actually fixed it. I wasn't binding the function that was calling the state. Thanks though!
