### ISSUE TITLE
Does this package let you import QR codes from the camera roll?

### ISSUE THREAD

**Issue by MiLeung** [moaazsidat/react-native-qrcode-scanner#183]
In the docs, [there's a suggestion to add the NSPhotoLibraryUsageDescription key to the info.plist](https://github.com/moaazsidat/react-native-qrcode-scanner#ios-10), but I don't see any methods related to importing  QR codes from the camera roll.

**Comment by moaazsidat** [comment]
Hey @MiLeung, we don't have support for that, but would be happy to accept PRs that introduce this functionality. I'd imagine some aspect of UI design to go into the feature as well to support a default 'plug-and-play' ability for the library.
