### ISSUE TITLE
Typescript errors with all ViewStyle props

### ISSUE THREAD

**Issue by dominictwlee** [moaazsidat/react-native-qrcode-scanner#184]
I'm feeding styles from StyleSheet.create into topViewStyle and cameraStyle, but getting errors that I think are related to wrong type definitions.

### How can it be reproduced?
![image](https://user-images.githubusercontent.com/34794189/58369297-4a946200-7ef0-11e9-8f6c-d5a93ae874be.png)
![image](https://user-images.githubusercontent.com/34794189/58369302-52540680-7ef0-11e9-8bd2-7f2502b1a4e3.png)

### Build details?

"react-native-qrcode-scanner": "^1.2.1",

**Comment by dominictwlee** [comment]
I think this should fix it. #185

**Comment by renatobenks** [comment]
@moaazsidat we should close this one because it seems to be fixed along with #185
