### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by TechSnake** [moaazsidat/react-native-qrcode-scanner#20]
Thanks for this useful plugin !

It is very easy to use but i just wonder why it vibrates so frequently even if when reactivateTimeout={2000}  or reactive={false}

cant it vibrate once not everytime when it see qcode 

Thanks in Advnace

**Comment by moaazsidat** [comment]
hey @TechSnake, you might want to use the `reactivate={false}` prop with the `reactivate()` method just released in 0.0.20 version. 

You can see further details here: https://github.com/moaazsidat/react-native-qrcode-scanner/issues/15
And docs for `reactivate()` here: https://github.com/moaazsidat/react-native-qrcode-scanner#reactivate

Please feel free to reopen the issue if this is still a problem. Cheers!

**Comment by lucky-mobile** [comment]
And docs for reactivate() here: https://github.com/moaazsidat/react-native-qrcode-scanner#reactivate
This problem not working at all.
could you help me about this problem?

**Comment by ekas** [comment]
> And docs for reactivate() here: https://github.com/moaazsidat/react-native-qrcode-scanner#reactivate
> This problem not working at all.
> could you help me about this problem?

+1
