### ISSUE TITLE
Not able to scan QRcode on android

### ISSUE THREAD

**Issue by KarishmaBothara** [moaazsidat/react-native-qrcode-scanner#21]
I am learning to use React Native. I made all the setting changes as mentioned in the article and used the sample example in my index.android.js. However when I run the project I don't see anything on the emulator. Am I doing something wrong?

**Comment by moaazsidat** [comment]
@KarishmaBothara couple of questions:
- Are you using Android studio to emulate the app?
- What version of Android are you emulating?
- Do you see any errors on the screen?
- Do you see any errors in the console?

**Comment by KarishmaBothara** [comment]
Yes, I am using Android studio 2.3.2 to emulate the app on device Nexus 5X API 24. However, I don't see any error on screen or console.

**Comment by KarishmaBothara** [comment]
Yes, I have changed NavigatorIOS. With that I see a camera with checkered background. Not able to test it.

**Comment by moaazsidat** [comment]
@KarishmaBothara so you are seeing the UI and the camera window render properly? 

You won't be able to test it unless you're running the app on a device. Not sure if Android Studio offers a way to build and run the app on your phone, but that's what you'd want to do to use the camera and be able to test it.

**Comment by KarishmaBothara** [comment]
Thanks @Moaazsidat . I was trying to test with the emulator. Many thanks for correcting me. Attached is the screenshot of how the UI and camera is render.
<img width="276" alt="capture" src="https://user-images.githubusercontent.com/29415595/27154460-395b0f3c-51a9-11e7-8d9c-9fe8c32e30e6.PNG">

**Comment by moaazsidat** [comment]
Yep, tested on Android studio Nexus 5X API 24. 

![screenshot 2017-06-15 13 34 45](https://user-images.githubusercontent.com/5963656/27194138-802650ea-51cf-11e7-9e47-c8a657ff546a.png)

Going to close this issue, marked as resolved, feel free to open another issue if you have further questions
