### ISSUE TITLE
Invalid RNPermission 'ios.permission.CAMERA' should be one of ()

### ISSUE THREAD

**Issue by java-james** [moaazsidat/react-native-qrcode-scanner#213]
After upgrading to latest (merge of PR #202) I am getting the following error:

<img width="284" alt="Screen Shot 2019-11-18 at 12 49 43 PM" src="https://user-images.githubusercontent.com/22756998/69016451-4bbbcd00-0a03-11ea-980a-fc37f732a8b2.png">

This error was reported by users in the PR.

### What's happening?
Throwing "Invalid RNPermission 'ios.permission.CAMERA' should be one of ()" on load of the page containing the scanner.

### How can it be reproduced?
Install react-native-qr-scanner @ 1.3.0
Follow instructions for dependencies and linking
Create a screen using the scanner

### Build details?
iOS 12.2
react-native-qr-scanner: 1.3.0
react-native: 0.61.4,

**Comment by evanoralph** [comment]
bump to this

**Comment by olethanh** [comment]
You need to add to your podfile
```
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
```
see https://github.com/react-native-community/react-native-permissions#ios

**Comment by WaveMeUp** [comment]
Same problem here, but for React Native 0.59.9. I don't have pods file in my project and to be honest do not want to have. I spent a lot of time and tried every solutions that was here or in react-native-permissions issues, but still get "Invalid RNPermission 'ios.permission.CAMERA' should be one" or other related stuff.

It would be great if someone could help, because right now I gave up.

**Comment by olethanh** [comment]
@WaveMeUp 
the problem is in that project and not this one, maybe see open an issue with them?

**Comment by berkio3x** [comment]
i am getting the exact same error. why this could be . as @olethanh said if i add
```
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
```
I get .
```
Unable to find a specification for `RNPermissions` depended upon by `Permission-Camera`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```
But i cannt use this as addthing this to podfile also installs an older version of react(0.11.0) & it messes up everything

**Comment by mzparacha** [comment]
I have same problem and even I added these 2 lines

`permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"`

And after that I also run pod install and uninstalled app from simulator and then re installed it but still I have same problem

**Comment by artyom-developer** [comment]
I have same :( something fix?

**Comment by artyom-developer** [comment]
> You need to add to your podfile
> 
> ```
>   permissions_path = '../node_modules/react-native-permissions/ios'
>   pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
> ```
> 
> see https://github.com/react-native-community/react-native-permissions#ios

I have same :( something fix?

**Comment by artyom-developer** [comment]
I fixed issue 
Xcode -> Product -> Clean Build Folder and Run iOS

**Comment by tomsotte** [comment]
> You need to add to your podfile
> 
> ```
>   permissions_path = '../node_modules/react-native-permissions/ios'
>   pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
> ```
> 
> see https://github.com/react-native-community/react-native-permissions#ios

I've fixed my issue as well:

1. Follow the guide on the link above and set the required permission in both the `Podfile` and the `Info.plist`
2. Clean the whole project with `npx react-native-clean-project`
3. Install the pods again with `cd ios && pod install`
4. Rebuild and launch the app on iOS simulator/device

**Comment by fujianjin6471** [comment]
> > You need to add to your podfile
> > ```
> >   permissions_path = '../node_modules/react-native-permissions/ios'
> >   pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
> > ```
> > 
> > 
> > see https://github.com/react-native-community/react-native-permissions#ios
> 
> I've fixed my issue as well:
> 
> 1. Follow the guide on the link above and set the required permission in both the `Podfile` and the `Info.plist`
> 2. Clean the whole project with `npx react-native-clean-project`
> 3. Install the pods again with `cd ios && pod install`
> 4. Rebuild and launch the app on iOS simulator/device

Succeed without cleaning, tks!

**Comment by TranDinhKhang** [comment]
Confirm that this worked for me. Please add this to Readme asap.

**Comment by Bautista-Baiocchi-lora** [comment]
> Confirm that this worked for me. Please add this to Readme asap.

Worked but you must follow it perfectly.

**Comment by tycooperaow** [comment]
How would this work if I build my project with expo?

**Comment by java-james** [comment]
@tycooperaow How about using an expo lib eg BarCodeScanner in your case?

@olethanh See readme has been updated - Does this resolve the issue here? Can't check no longer consuming the lib

**Comment by olethanh** [comment]
Sorry I'm not working on the app that was using this project anymore so I can't check

**Comment by renatobenks** [comment]
I'm closing this one, once it's solved for too long already!
