### ISSUE TITLE
dotcode scan in qrcode scanner

### ISSUE THREAD

**Issue by musadiq-jinbade** [moaazsidat/react-native-qrcode-scanner#215]
### Build details?

can we scan dotcode in react native qrcode scanner

this are the type in react native qrcode scanner aztec: any, code128: any, code39: any, code39mod43: any, code93: any, ean13: any, ean8: any, pdf417: any, qr: any, upce: any, interleaved2of5: any, itf14: any, datamatrix: any

can we add Dotcode in that?

**Comment by moaazsidat** [comment]
sure go for it, will accept PRs
