### ISSUE TITLE
react-native-permissions/src/constants.ts: Unexpected token (2:59)

### ISSUE THREAD

**Issue by roshan-p** [moaazsidat/react-native-qrcode-scanner#216]
I got this error after I run ios simulator.
> node_modules/react-native-permissions/src/constants.ts: Unexpected token (2:59)
  1 | export const ANDROID = Object.freeze({
'>' 2 |   ACCEPT_HANDOVER: 'android.permission.ACCEPT_HANDOVER' as const,
    |                                                            ^
  3 |   ACCESS_BACKGROUND_LOCATION: 'android.permission.ACCESS_BACKGROUND_LOCATION' as const,
  4 |   ACCESS_COARSE_LOCATION: 'android.permission.ACCESS_COARSE_LOCATION' as const,
  5 |   ACCESS_FINE_LOCATION: 'android.permission.ACCESS_FINE_LOCATION' as const,

 "react-native": "0.59.10",
 "react-native-qrcode-scanner": "^1.3.1",
 "react-native-permissions": "^2.0.3",

**Comment by moaazsidat** [comment]
> node_modules/react-native-permissions/src/constants.ts
seems like a problem in react-native-permissions
