### ISSUE TITLE
Empty camera permissions rationale popup android

### ISSUE THREAD

**Issue by aaroncornelissen** [moaazsidat/react-native-qrcode-scanner#218]
When I where testing my application I discovered an empty popup on android before I got the permission popup. When I googled the problem I found an issue that solved my problem: https://github.com/react-native-community/react-native-camera/issues/232. 

![Screenshot_20191204-152922](https://user-images.githubusercontent.com/57479235/70151231-95ffa800-16ab-11ea-8431-df58d04c511b.jpg)

If I pass androidCameraPermissionOptions: null to cameraProps I don't get the empty alert anymore. So I hope this solution helps to improve the scanner.

Build details
react-native: "0.61.5"
react-native-qrcode-scanner: "1.3.1"
react-native-camera: "3.8.0"

**Comment by moaazsidat** [comment]
Will accept PRs fixing this.
