### ISSUE TITLE
bottomContent loses height configuration when the QR scanner is inside a KeyboardAwareScrollView

### ISSUE THREAD

**Issue by franmio** [moaazsidat/react-native-qrcode-scanner#221]
When I add the QR Scanner code inside the KeyboardAwareScrollView from the 'react-native-keyboard-aware-scroll-view' library, the bottomContent loses the height configuration.
I need to use this library because I want to add some TextInputs and they are overlapped otherwise.
### What's happening?

Without KeyboardAwareScrollView
```
<QRCodeScanner
        showMarker={true}
        vibrate={false}
        ref={(camera) => scanner = camera}
        onRead={nuevo}
        topContent={
          <Text style={styles.centerText}>
            Go to <Text style={styles.textBold}>qr-code-generator.com</Text> on your computer and create the QR code.
          </Text>
        }
        bottomContent={(<View style={{height: '100%', width: '100%',backgroundColor:'red'}}><Text>hello</Text></View>)}
      />
```
![image](https://user-images.githubusercontent.com/22008372/71449405-131eba00-274c-11ea-9f01-9b5d89d6871e.png)

With KeyboardAwareScrollView
```
      <KeyboardAwareScrollView enableResetScrollToCoords={false} style={{ flex: 1 }}>
      <QRCodeScanner
        showMarker={true}
        vibrate={false}
        ref={(camera) => scanner = camera}
        onRead={nuevo}
        topContent={
          <Text style={styles.centerText}>
            Go to <Text style={styles.textBold}>qr-code-generator.com</Text> on your computer and create the QR code.
          </Text>
        }
        bottomContent={(<View style={{height: '100%', width: '100%',backgroundColor:'red'}}><Text>hello</Text></View>)}
      />
      </KeyboardAwareScrollView>
```
![image](https://user-images.githubusercontent.com/22008372/71449409-1dd94f00-274c-11ea-8a67-415809f861a1.png)

**Comment by moaazsidat** [comment]
I would suggest using `react-native-camera` directly if you're trying to change the UI significantly. 
Alternatively, if this is a valid broad use case, will accept PRs bringing this functionality to this library.

**Comment by franmio** [comment]
> 
> 
> I would suggest using `react-native-camera` directly if you're trying to change the UI significantly.
> Alternatively, if this is a valid broad use case, will accept PRs bringing this functionality to this library.

I only need to add two TextInputs and I wrapped all in a KeyboardAwareScrollView to avoid the keyboard overlapping...
