### ISSUE TITLE
Require cycle warn

### ISSUE THREAD

**Issue by acerbastimur** [moaazsidat/react-native-qrcode-scanner#223]
Debugger says 'Require cycle warn'

### What's happening?
I'm using "^1.3.1" version. When I use the component purely, it throws this error on both Android & Ios.

![Screen Shot 2020-01-16 at 01 02 42](https://user-images.githubusercontent.com/33218120/72475601-4bba2c80-37fc-11ea-9e39-d8a17a535e1b.png)

How can I solve it ?

**Comment by moaazsidat** [comment]
hmm, not entirely sure, do you have a repo that you can point to where this is reproduced?

**Comment by AzzouDuGhetto** [comment]
Same problem, it happend because mode.js import version.js who import mode.js etc.

A workaround will be to delete 'var Version = require('./version')' in mode.js since version.js is already imported in the first place ? Not sure if this is a suitenable way to do this.
