### ISSUE TITLE
What react-native-qrcode-scanner offers that react-native-camera doesn't?

### ISSUE THREAD

**Issue by NelsonPRSousa** [moaazsidat/react-native-qrcode-scanner#224]
I was reading react-native-camera [documentation](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#onbarcoderead) and seems that react-native-camera already reads QR codes.

> The following barcode types can be recognised:
>
> aztec
> code128
> code39
> code39mod43
> code93
> ean13 (iOS converts upca barcodes to ean13 by adding a leading 0)
> ean8
> pdf417
> **qr**
> upce
> interleaved2of5 (when available)
> itf14 (when available)
> datamatrix (when available)

What am I missing here?

**Comment by moaazsidat** [comment]
from the [readme](https://github.com/moaazsidat/react-native-qrcode-scanner/blob/master/README.md): 

> This module was originally written because the author couldn't find a module that could be simply plugged into a project without requiring too much setup.

Also see the screenshot in the readme for the user interface this offers, if you'd like anything too different, I'd recommend implementing using `react-native-camera`

**Comment by NelsonPRSousa** [comment]
Thanks, I wasn't completely sure regarding the differences. 👍
