### ISSUE TITLE
NativeModule.RNPermissions is null

### ISSUE THREAD

**Issue by estevanpedro** [moaazsidat/react-native-qrcode-scanner#225]
`react-native-permissions: NativeModule.RNPermissions is null. ` after open <QRCodeScanner ... />
### What's happening?

I have done everything right in the setup, i checked several times, and i'm getting this error on android.
### How can it be reproduced?

I installed react-native-camera and then react-native-qrcode-scanner
### Build details?

I'm using React-native: 60.5 with hooks and typescript
Android

**Comment by ardiankristo** [comment]
i had this a while ago and after i follow the setup from here [https://github.com/react-native-community/react-native-permissions](url) it actually fixes that 

> by adding all the permissions in the AndroidManifest.xml
`<uses-permission android:name="android.permission.ACCEPT_HANDOVER" />
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACTIVITY_RECOGNITION" />
  <uses-permission android:name="android.permission.ANSWER_PHONE_CALLS" />
  <uses-permission android:name="android.permission.BODY_SENSORS" />
  <uses-permission android:name="android.permission.CALL_PHONE" />
  <uses-permission android:name="android.permission.CAMERA" />
  <uses-permission android:name="android.permission.GET_ACCOUNTS" />
  <uses-permission android:name="android.permission.PROCESS_OUTGOING_CALLS" />
  <uses-permission android:name="android.permission.READ_CALENDAR" />
  <uses-permission android:name="android.permission.READ_CALL_LOG" />
  <uses-permission android:name="android.permission.READ_CONTACTS" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />
  <uses-permission android:name="android.permission.READ_PHONE_STATE" />
  <uses-permission android:name="android.permission.READ_SMS" />
  <uses-permission android:name="android.permission.RECEIVE_MMS" />
  <uses-permission android:name="android.permission.RECEIVE_SMS" />
  <uses-permission android:name="android.permission.RECEIVE_WAP_PUSH" />
  <uses-permission android:name="android.permission.RECORD_AUDIO" />
  <uses-permission android:name="android.permission.SEND_SMS" />
  <uses-permission android:name="android.permission.USE_SIP" />
  <uses-permission android:name="android.permission.WRITE_CALENDAR" />
  <uses-permission android:name="android.permission.WRITE_CALL_LOG" />
  <uses-permission android:name="android.permission.WRITE_CONTACTS" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="com.android.voicemail.permission.ADD_VOICEMAIL" />`

**Comment by kirame09** [comment]
That doesn't solve the issue, any update on this one pls?

**Comment by AndreLuizGarcia** [comment]
I am having the same issue.
Some update?

**Comment by AdiCutitoiu** [comment]
This worked for me

`
npm install react-native-permissions --save
react-native link react-native-permissions
`

**Comment by givionte** [comment]
Same issue here.  I followed the guide exactly, including adding permissions.  I am not using expo, I have a full react-native project.  Already have tried removing node_modules, cleaning cache,reinstalling, but got nothing.  All packages successfully linked. @estevanpedro @AndreLuizGarcia  Did you find a solution that worked for you?

> G:\development\TableForTwo\node_modules\react-native\Libraries\Core\ExceptionsManager.js:44 Error: react-native-permissions: NativeModule.RNPermissions is null. To fix this issue try these steps:
reportException | @ | G:\development\Table…ptionsManager.js:44
-- | -- | --
  | handleException | @ | G:\development\Table…tionsManager.js:113
  | handleError | @ | G:\development\Table…ErrorHandling.js:23
  | reportFatalError | @ | G:\development\Table…s\error-guard.js:49
  | guardedLoadModule | @ | G:\development\Table…ills\require.js:204
  | metroRequire | @ | G:\development\Table…ills\require.js:128
  | (anonymous) | @ | G:\development\Table…\FaceDetector.js:60
  | executeApplicationScript | @ | debuggerWorker.js:37
  | (anonymous) | @ | debuggerWorker.js:62



My Package.json

```
"@apollo/react-hooks": "^3.1.3",
    "@react-native-community/async-storage": "^1.8.1",
    "@types/redux-logger": "^3.0.7",
    "@types/styled-components": "^5.0.1",
    "apollo-cache-inmemory": "^1.6.5",
    "apollo-client": "^2.6.8",
    "apollo-link-http": "^1.5.16",
    "graphql": "^14.6.0",
    "graphql-tag": "^2.10.3",
    "react": "16.9.0",
    "react-apollo": "^3.1.3",
    "react-native": "0.61.5",
    "react-native-camera": "^3.21.0",
    "react-native-clean-project": "^3.3.0",
    "react-native-permissions": "^2.0.10",
    "react-native-qrcode-scanner": "^1.4.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "socket.io-client": "^2.3.0",
    "styled-components": "^5.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "@types/jest": "^24.0.24",
    "@types/react-native": "^0.60.25",
    "@types/react-redux": "^7.1.7",
    "@types/react-test-renderer": "16.9.1",
    "@typescript-eslint/eslint-plugin": "^2.12.0",
    "@typescript-eslint/parser": "^2.12.0",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0",
    "redux-logger": "^3.0.6",
    "typescript": "^3.7.3"
  },
```

**Comment by imrvelj** [comment]
Happened to me with `react-native` `0.60.4` and managed to fix it by just installing the `react-native-permissions` package ie. `npm i -S react-native-permissions`

**Comment by renatobenks** [comment]
I'll be closing this issue once this problem seems to be already solved because it's regarding to `react-native-permissions` integrating and not to the `react-native-qrcode-scanner` itself
