### ISSUE TITLE
FlashMode doesn`t work

### ISSUE THREAD

**Issue by igormoraesdev** [moaazsidat/react-native-qrcode-scanner#228]
hey guys, i can`t use flashMode, i need to change everytime in node_modules the prop on flashMode, anyone can help? my version is "react-native-qrcode-scanner": "^1.3.1",

my code 

`
import QRCodeScanner from 'react-native-qrcode-scanner';
import { RNCamera as Camera } from 'react-native-camera';

<QRCodeScanner
        ref={ref => setQrRef(ref)}
        flashMode={
          flash
            ? Camera.Constants.FlashMode.torch
            : Camera.Constants.FlashMode.off
        }
        customMarker={
          <QrCodeBackground
            navigation={navigation}
            lightsOn={lightsOn}
            onShowCard={onShowCard}
            showCard={showCard}
          />
        }
        cameraStyle={{ height }}
        onRead={onReadQrCode}
        showMarker
      />
`

**Comment by danhnguyeen** [comment]
This option worked for me
```
import {RNCamera} from 'react-native-camera';

<QRCodeScanner
        ref={node => {
          this.scanner = node;
        }}
        onRead={onScanSuccess}
        cameraProps={{flashMode: flashlight ? RNCamera.Constants.FlashMode.torch : RNCamera.Constants.FlashMode.off }}
 />
```
