### ISSUE TITLE
Reactivate of scanning not working when navigating back from another screen

### ISSUE THREAD

**Issue by DuranMoodley** [moaazsidat/react-native-qrcode-scanner#230]
I open the camera to scan and set the reactivate prop to false. When scan is successful i navigate to another screen. When i navigate back to the camera to scan again, no scan works. I cannot re-scan again. I have tried setting the reactivate prop to true and the reactivateTimeout to a large time constraint. However, the scanning continuously works even when the screen is in the background. Please assist with this issue.

  <QRCodeScanner
        onRead={onSuccess}
        showMarker={true}
        reactivate={false}
        checkAndroid6Permissions={true}
       //reactivateTimeout={5000}
        ref={elem => {
          // QRCodeScanner = elem;
          // QRCodeScanner.reactivate()
        }}
        cameraStyle={{ height: Dimensions.get('window').height - 150 }}
      />

Only testing on Android only

**Comment by zoneint** [comment]
Apparently that was a problem with react navigation closing the camera:
https://github.com/react-native-community/react-native-camera/issues/2698

For now I'm working around this using NavigationEvents to remount my QRCodeScanner everytime my screen get Focused.


<NavigationEvents 
    onDidFocus={()=>this.setState({showCamera:true})}
    onWillBlur={()=>this.setState({showCamera:false})}
/>
{this.state.showCamera&&
    <QRCodeScanner
        cameraStyle={{height:'100%', width:'100%',overflow: 'hidden'}}
        onRead={this.onSuccess}
        reactivate={true}
        reactivateTimeout={2000}
        fadeIn
    />}

**Comment by NirmalsinhRathod** [comment]
@zoneint Thanks for your help. You saved my time :)

**Comment by nikoWah** [comment]
Met the same issue, thanks for the idea. 👍

**Comment by renatobenks** [comment]
I'm closing this one as it doesn't seem to be related to `react-native-qrcode-scanner` itself anymore, and thank you for the help @zoneint
