### ISSUE TITLE
App getting crashed on QR code scan 

### ISSUE THREAD

**Issue by sharad-epam** [moaazsidat/react-native-qrcode-scanner#232]
App getting crashed on QR code scan  and when try open again its not opening 

### What's happening?

I am using the same example which is provided in the library , but some how i am not getting success in executing that  example successfully.
### How can it be reproduced?

`import React from 'react';

import {StyleSheet, Text, View, TouchableOpacity, Linking} from 'react-native';
import QRCodeScanner from 'react-native-qrcode-scanner';

const App = props => {
  const onSuccess = e => {
    //Linking.openURL(e.data).catch(err => console.log(err));
  };
  return (
    <View>
      <QRCodeScanner
        onRead={onSuccess}
        topContent={<Text style={styles.centerText}>Scan the QR code</Text>}
        permissionDialogMessage={
          <Text>Please, provide your Camera Permission</Text>
        }
        bottomContent={
          <TouchableOpacity style={styles.buttonTouchable}>
            <Text style={styles.buttonText}>OK. Got it!</Text>
          </TouchableOpacity>
        }
      />
    </View>
  );
};
const styles = StyleSheet.create({
  centerText: {
    flex: 1,
    fontSize: 18,
    padding: 32,
    color: '#777',
  },
  textBold: {
    fontWeight: '500',
    color: '#000',
  },
  buttonText: {
    fontSize: 21,
    color: 'rgb(0,122,255)',
  },
  buttonTouchable: {
    padding: 16,
  },
});

export default App;
`
### Build details?

 "react": "16.9.0",
  "react-native": "0.61.5",
 "react-native-permissions": "^2.0.9",
 "react-native-qrcode-scanner": "^1.3.1",

**Comment by sharad-epam** [comment]
> App getting crashed on QR code scan and when try open again its not opening
> 
> ### What's happening?
> I am using the same example which is provided in the library , but some how i am not getting success in executing that example successfully.
> 
> ### How can it be reproduced?
> `import React from 'react';
> 
> import {StyleSheet, Text, View, TouchableOpacity, Linking} from 'react-native';
> import QRCodeScanner from 'react-native-qrcode-scanner';
> 
> const App = props => {
> const onSuccess = e => {
> //Linking.openURL(e.data).catch(err => console.log(err));
> };
> return (
> 
> <QRCodeScanner
> onRead={onSuccess}
> topContent={Scan the QR code}
> permissionDialogMessage={
> Please, provide your Camera Permission
> }
> bottomContent={
> 
> OK. Got it!
> 
> }
> />
> 
> );
> };
> const styles = StyleSheet.create({
> centerText: {
> flex: 1,
> fontSize: 18,
> padding: 32,
> color: '#777',
> },
> textBold: {
> fontWeight: '500',
> color: '#000',
> },
> buttonText: {
> fontSize: 21,
> color: 'rgb(0,122,255)',
> },
> buttonTouchable: {
> padding: 16,
> },
> });
> 
> export default App;
> `
> 
> ### Build details?
> "react": "16.9.0",
> "react-native": "0.61.5",
> "react-native-permissions": "^2.0.9",
> "react-native-qrcode-scanner": "^1.3.1",

**Comment by Fedorrychkov** [comment]
I had a similar problem, I was getting the error from https://github.com/facebook/react-native/issues/16769

**Comment by shiroze** [comment]
> App getting crashed on QR code scan and when try open again its not opening
> 
> ### What's happening?
> I am using the same example which is provided in the library , but some how i am not getting success in executing that example successfully.
> 
> ### How can it be reproduced?
> `import React from 'react';
> 
> import {StyleSheet, Text, View, TouchableOpacity, Linking} from 'react-native'; import QRCodeScanner from 'react-native-qrcode-scanner';
> 
> const App = props => { const onSuccess = e => { //Linking.openURL(e.data).catch(err => console.log(err)); }; return ( <QRCodeScanner onRead={onSuccess} topContent={Scan the QR code} permissionDialogMessage={ Please, provide your Camera Permission } bottomContent={ OK. Got it! } /> ); }; const styles = StyleSheet.create({ centerText: { flex: 1, fontSize: 18, padding: 32, color: '#777', }, textBold: { fontWeight: '500', color: '#000', }, buttonText: { fontSize: 21, color: 'rgb(0,122,255)', }, buttonTouchable: { padding: 16, }, });
> 
> export default App; `
> 
> ### Build details?
> "react": "16.9.0", "react-native": "0.61.5", "react-native-permissions": "^2.0.9", "react-native-qrcode-scanner": "^1.3.1",

So what's the solution from the problem you face here ?
I want to know because I facing this issue now.
