### ISSUE TITLE
Could not determine the dependencies of task ':react-native-camera:compileMlkitReleaseAidl'. 

### ISSUE THREAD

**Issue by VincentKunXie** [moaazsidat/react-native-qrcode-scanner#243]
Got the following error when building a release apk for my project (project used qr code scanner, camera and permission) 

**could not determine the dependencies of task ':react-native-camera:compileMlkitReleaseAidl'.
> Could not resolve all task dependencies for configuration ':react-native-camera:mlkitReleaseCompileClasspath'.**

`Could not find com.google.android.gms:play-services-vision-image-label:12.0.1.
     Required by:
         project :react-native-camera > com.google.firebase:firebase-ml-vision:19.0.3
   > Could not find com.google.android.gms:play-services-clearcut:12.0.1.
     Required by:
         project :react-native-camera > com.google.firebase:firebase-ml-vision-face-model:17.0.2
         project :react-native-camera > com.google.firebase:firebase-ml-common:17.0.0
   > Could not find com.google.android.gms:play-services-flags:12.0.1.
     Required by:
         project :react-native-camera > com.google.firebase:firebase-ml-vision-face-model:17.0.2
   > Could not find com.google.android.gms:play-services-phenotype:12.0.1.
     Required by:
         project :react-native-camera > com.google.firebase:firebase-ml-common:17.0.0
   > Could not find com.google.android.gms:play-services-stats:12.0.1.
     Required by:
         project :react-native-camera > com.google.firebase:firebase-iid:17.0.3`

### What's happening?

Building debug version was fine, the error throw u when building release apk

### How can it be reproduced?

`subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "28.0.0"
            }
            if (details.requested.group == 'com.google.android.gms'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "12.0.1"
            }
        }
    }`

I have to include this, or I will get the **java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;** error, in this way it will build release apk, but the app will crash when start

### Build details?

Versions I used:
    **"react-native-camera": "^3.21.0",
    "react-native-permissions": "^2.0.10",
    "react-native-qrcode-scanner": "^1.4.0",**

The following are my build files:

**Project build.gradle**
`buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 21
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "17.0.2"
        googlePlayServicesLocationVersion = "16.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
	    classpath 'com.bugsnag:bugsnag-android-gradle-plugin:4.+'
    }
}

allprojects {
    repositories {

        google()
        mavenLocal()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }

        configurations.all {
            resolutionStrategy.eachDependency { DependencyResolveDetails details ->
                def requested = details.requested
                if (requested.group == 'com.google.android.gms') {
                    details.useVersion '12.0.1'
                }
                if (requested.module == 'com.google.firebase') {
                    details.useVersion '12.0.1'
                }
            }
        }

    }
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "28.0.0"
            }
            if (details.requested.group == 'com.google.android.gms'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "12.0.1"
            }
        }
    }

    afterEvaluate {
                android {
                    compileSdkVersion 28
                    buildToolsVersion "28.0.3"

                    defaultConfig {
                        targetSdkVersion 28
                    }
                }
    }

}`

**APP build.gradle**
`android {
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    defaultConfig {
        applicationId "************"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 22
        versionName "1.3.0"
        ndk {
            abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
        }
        manifestPlaceholders = [onesignal_app_id: "*************",
                                onesignal_google_project_number: "***************"]
        missingDimensionStrategy 'react-native-camera', 'general'
    }
    dexOptions {
        javaMaxHeapSize "2g"
        preDexLibraries = false;
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            aaptOptions.cruncherEnabled=false
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {

    implementation project(':react-native-permissions')
    implementation project(':react-native-camera')
    implementation project(':bugsnag-react-native')
    implementation project(':@react-native-community_async-storage')
    implementation project(':react-native-i18n')
    implementation project(':react-native-svg')
    implementation project(':react-native-sunmi-inner-printer')
    implementation project(':react-native-sound-player')
    implementation project(':react-native-code-push')
    implementation project(':react-native-splash-screen')
    implementation project(':react-native-onesignal')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.android.gms:play-services:12.0.1'

}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

bugsnag {
    ndk true
    sharedObjectPath "app/build/jni/libs"
}`

**Please help!!! thanks a lot** 👍

**Comment by renatobenks** [comment]
are you still facing it @VincentKunXie?

**Comment by VincentKunXie** [comment]
> are you still facing it @VincentKunXie?

Problem solved after upgrading to RN >= 0.6

**Comment by renatobenks** [comment]
thank you for sharing @VincentKunXie!

but did you mean `>=0.60`, right? 🤔
