### ISSUE TITLE
cameraProps produce issues for Android.

### ISSUE THREAD

**Issue by fahadibrahimbutt** [moaazsidat/react-native-qrcode-scanner#249]
Everything was working fine.
Then i try to restrict scanning for QRCode & PDF417.

I use this line to restrict scanning:
cameraProps= {{barCodeTypes: ["org.iso.QRCode", "org.iso.PDF417"]}}

After this, iOS works fine. But Android stops scanning everything.

**Comment by renatobenks** [comment]
@fahadibrahimbutt could you provide a demo repo reproducing this issue to make it easy to help you?

**Comment by Zo2m4bie** [comment]
@fahadibrahimbutt just add one more type
cameraProps={{ barCodeTypes: ['QR_CODE', 'org.iso.QRCode', 'org.iso.PDF417'] }}

**Comment by renatobenks** [comment]
lets us know @fahadibrahimbutt if it worked because as @Zo2m4bie commented it seem that will be work

**Comment by eteamIH** [comment]
@Zo2m4bie the solution you shared works for QR Codes. Can you share a way to scan all supported barCodeTypes other than QR Codes?
