### ISSUE TITLE
publishing to NPM automatically via github on releasing bump version

### ISSUE THREAD

**Issue by renatobenks** [moaazsidat/react-native-qrcode-scanner#256]
### What's happening?

Currently, to publish an updated version of this package takes a while because it needs to be done totally manually.

### What could it be done?

To solve that it could be configured to publish automatically to every release made as new pushed tags, using the github actions which give us a setup well done to do that.

**Comment by moaazsidat** [comment]
Fixed by https://github.com/moaazsidat/react-native-qrcode-scanner/pull/306
