### ISSUE TITLE
Android The camera blocked the topContent

### ISSUE THREAD

**Issue by wadeyw** [moaazsidat/react-native-qrcode-scanner#260]
### What's happening?
Like below screenshot in emulator, the camera will cover the top content, I didn't do any styling.

![image](https://user-images.githubusercontent.com/20250120/82519612-a8d04100-9b54-11ea-9618-daae721d164f.png)

 "react-native-camera": "^3.26.0",
 "react-native": "0.62.2",
"react-native-qrcode-scanner": "^1.4.1",

**Comment by Minhoko** [comment]
Any update on this?

**Comment by Minhoko** [comment]
@wadeyw Did you find a solution on this?

**Comment by wadeyw** [comment]
> @wadeyw cameraStyle={{overflow: 'hidden'}} is worked for me

yea, thanks, was solved the same way
cameraProps={{ratio: '1:1', overflow: 'hidden'}}

**Comment by renatobenks** [comment]
thank you for sharing it @wadeyw
