### ISSUE TITLE
borderRadius does not work

### ISSUE THREAD

**Issue by nandantal** [moaazsidat/react-native-qrcode-scanner#262]
borderRadius doesn't work

### What's happening?
I am trying to create one rounded corner camera view but borderRadius doesn't work. Is there any way to do it ?

Platform : iOS

### Code snippet : 
containerStyle={{position: 'absolute', height: 200, width: 200, borderRadius: 100}}
cameraStyle={{position: 'absolute', height: 200, width: 200, borderRadius: 100}}

**Comment by nandantal** [comment]
cameraStyle={{overflow:'hidden', position: 'absolute', height: 200, width: 200, borderRadius: 100}}
works. closing the issue.

**Comment by avillarubia** [comment]
> cameraStyle={{overflow:'hidden', position: 'absolute', height: 200, width: 200, borderRadius: 100}} works. closing the issue.

thank you
