### ISSUE TITLE
Style notAuthorizedView in android.

### ISSUE THREAD

**Issue by 100rabhchauhan** [moaazsidat/react-native-qrcode-scanner#268]
I need to style the notAuthorizedView component for android. Any suggestions. I am using react-native-qrcode-scanner 1.4.1

**Comment by renatobenks** [comment]
what kind of suggestion of style do you want? I didn't get you on that yet, can you explain it better?

Just to make sure that you're pretty clear about the uses of `notAuthorizatedView` prop. This is directly related to which component will render when the user refuses the permission access, required by the camera

**Comment by renatobenks** [comment]
I'm closing this one for inactivity reasons.
