### ISSUE TITLE
iPhone X - Exception thrown while executing UI block

### ISSUE THREAD

**Issue by Nirodha26** [moaazsidat/react-native-qrcode-scanner#271]
QRCodeScanner throws an error on iPhone X device. Works fine in other devices.

### What's happening?
Unable to render QRCodeScanner. It throws following exception.

![image](https://user-images.githubusercontent.com/11444050/85021086-f6a98a80-b18e-11ea-9f78-3226a58e8dd1.png)

### How can it be reproduced?
This can be reproduced with the example given in the library documentation.

` <QRCodeScanner
        onRead={this.onSuccess}
        topContent={
          <Text style={styles.centerText}>
            Go to{' '}
            <Text style={styles.textBold}>wikipedia.org/wiki/QR_code</Text> on
            your computer and scan the QR code.
          </Text>
        }
        bottomContent={
          <TouchableOpacity style={styles.buttonTouchable}>
            <Text style={styles.buttonText}>OK. Got it!</Text>
          </TouchableOpacity>
        }
      />`

### Build details?
react-native : 0.60.0
react-native-camera: 3.28.0
react-native-permissions: 2.1.5

**Comment by Nirodha26** [comment]
Upgrading react-native-camera to 3.30.0 and pod install solved the issue.

**Comment by renatobenks** [comment]
thank you for hsaring @Nirodha26
