### ISSUE TITLE
How can I do full screen view of the phone like WeChat had on Scan QR

### ISSUE THREAD

**Issue by jayzyaj** [moaazsidat/react-native-qrcode-scanner#277]
### What's happening?
The current view of my camera or QR code scanner is not in full height and I want to make it full height of the screen. How can I do that?

### How can it be reproduced?
I tried to modify `cameraStyle={{ flex: 1, maxHeight: '100%' }}` but its still not giving full screen view. Is it that I am just doing it wrong?

### Build details?
```
"react-native": "0.62.2"
"react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera.git"
"react-native-qrcode-scanner": "^1.4.1"
```

**Comment by renatobenks** [comment]
alright, can you show in advance how looks like the camera at the screen within such style in `cameraProps` been used, to understand better what you want as result.

Also, did you try, or even consider, to use other props to change the header and bottom style? these parts are shown at scanner by default and might be avoiding you to do that as you trying to.

**Comment by mkdesilva** [comment]
You can use the example to achieve this.
https://github.com/moaazsidat/react-native-qrcode-scanner/blob/ed81c27dadb44be063740cc819eba7c2a3720db5/examples/fullScreen.ios.js

**Comment by renatobenks** [comment]
I'll gonna give a try on it @mkdesilva, thank you for that suggestiin

**Comment by VSV6** [comment]
In my case, `Dimensions.get('window').height` this code was enough. It made a full-screen scanner. Use this code in cameraStyle prop. It'll work :)
