### ISSUE TITLE
Verify qr-code origin / authenticate data

### ISSUE THREAD

**Issue by assafb81** [moaazsidat/react-native-qrcode-scanner#28]
Hi,
I am not sure this is the right location but:
what is the best way to validate the QR-Code I scan with my application (using react-native-camera).
I want to show an error message, or something like that, when the qr-code was not sent from specific location?

something like digital signature or RS256/HS256 scenarios (https://stackoverflow.com/questions/39239051/rs256-vs-hs256-whats-the-difference)

**Comment by moaazsidat** [comment]
hey @assafb81, wondering if you can do that inside the `onRead` function passed as a prop. if you're validating asynchronously, a promise with callback that renders an alert modal if in case the QR code wasn't verified might be a way to go (see code sketch below). 
Let me know if that answers your question. 

```
onRead = (e) => {
  qrCodeData = e.data;
  getAuthInfo(qrCodeData)
    .then(resp => {
      if (resp.error) {
        this.setState({
          showErrorModal: true,
          errorMessage: resp.error
        })
      }
    }
}
```

**Comment by assafb81** [comment]
I want that the qrCodeData will contain a private key that will be validated by a public key that the application will hold....Is it possible to have multiple private keys with one public key?

**Comment by moaazsidat** [comment]
Yep. You can also directly use `sha256(...)` in place of `getAuthInfo()` since that function also returns a promise, let me know if you run into any issues with this.

**Comment by moaazsidat** [comment]
Going to close this, feel free to reopen if this still needs fixing. Also, if possible/interested, send a PR for an example covering this use case, definitely think others looks to auth/verify may benefit from this.

**Comment by assafb81** [comment]
sha256() only use to hash a string, but its not going to help:
sha256(string) = hashedString

I don't see how this can help...I've tried that - [https://github.com/itinance/react-native-sha256/issues/3](url)
