### ISSUE TITLE
App get closed when navigating to Screen That contains QRCodeScanner

### ISSUE THREAD

**Issue by Rachidelmahmoudi** [moaazsidat/react-native-qrcode-scanner#281]
### Info project ?

System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
    Memory: 464.33 MB / 3.87 GB
  Binaries:
    Node: 12.5.0 - C:\laragon\bin\nodejs\node-v12\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\laragon\bin\nodejs\node-v12\npm.CMD
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4

### I implemented the Compenemt as below 
```
render() {
    return (
      <QRCodeScanner
        onRead={() => this.onSuccess}
        flashMode={RNCamera.Constants.FlashMode.torch}
        topContent={
          <Text style={styles.centerText}>
            Go to{' '}
            <Text style={styles.textBold}>wikipedia.org/wiki/QR_code</Text> on
            your computer and scan the QR code.
          </Text>
        }
        bottomContent={
          <TouchableOpacity style={styles.buttonTouchable}>
            <Text style={styles.buttonText}>OK. Got it!</Text>
          </TouchableOpacity>
        }
      />
    );
  }
```
Inside screen class.

### The issue
When I navigate to that screen the app close itself without returning any error and  the node server still listing.
Any suggestion please ?

**Comment by renatobenks** [comment]
you probably are facing a problem non-related to the `react-native-qrcode-scanner` itself, but instead with your code. Can you give us more details about such an error?

**Comment by Rachidelmahmoudi** [comment]
Thanks @renatobenks .
I run my app with `npx react-native run-android` commad.
I do not get any error in the console so I can't see the log.
Best regards.

**Comment by renatobenks** [comment]
what about your build? it has been built successfully as well?
