### ISSUE TITLE
Version to be used on RN 0.59.3 without AndroidX support

### ISSUE THREAD

**Issue by krakzk** [moaazsidat/react-native-qrcode-scanner#295]
I am adding the plugin to an existing 0.59.3 app. But the latest version of this plugin and supporting camera and permissions plugins are not working in that.

**Comment by SahanDll** [comment]
try
npx jetifier -r

**Comment by krakzk** [comment]
@SahanDll I cant migrate my application to Androidx currently. I wanted to get the versions of qrcode scanner and react-native-camera plugin in 0.59.3. I tried with 0.0.19 and 1.10.0 versions respectivley.
It would be helpful if i get that

**Comment by krakzk** [comment]
I got it working.
Using
"react-native-camera": "^1.10.0",
    "react-native-qrcode-scanner": "0.0.19"

@SahanDll Thank you for the reply  :)
