### ISSUE TITLE
Any progress on android?

### ISSUE THREAD

**Issue by pvpshoot** [moaazsidat/react-native-qrcode-scanner#3]
Hi! Thank you for this package.
Just use it for app, and don't want to use another package only for android.
Any progress on android?

**Comment by moaazsidat** [comment]
Hey @pvpshoot, thanks for using this package! 
I haven't had time to look into Android support yet. Might look into it over the next two weeks. Feel free to submit a PR if you've worked on adding Android support to the package.

**Comment by justinireland** [comment]
The camera module supports Android so what is it about this package that isn't cross platform?

**Comment by moaazsidat** [comment]
I think it might be mostly styling, and ensuring that works across different screen sizes. I don't have an Android device on me to test and verify that the package works as expected.

**Comment by alexbowers** [comment]
Is there anything i can do to assist in getting this to android?

**Comment by moaazsidat** [comment]
@alexbowers A couple of things we could do to start off:
- Test this library in a simulated Android environment (Android studio)
- Test this library with a couple of Android devices 
- Make a set of tasks to fix what's broken
- Update with Android examples (or one that at platform agnostic)

Thanks!

**Comment by alexbowers** [comment]
#7
