### ISSUE TITLE
Setup CI for publishing on merges to master

### ISSUE THREAD

**Issue by moaazsidat** [moaazsidat/react-native-qrcode-scanner#302]
This should involve setting up Travis/Github Actions or similar so that every merge to the master branch can be released with a version bump. 

This will avoid having to manually publish on every change.

**Comment by renatobenks** [comment]
great @moaazsidat! let's make it work, do you need some help?

**Comment by renatobenks** [comment]
the react-native-camera has something similar working very well with a pretty easy config, and it does seem to publish on npm by this plugin: https://github.com/semantic-release/npm, following the next snippets:

https://github.com/react-native-camera/react-native-camera/blob/42388be530f4a791ff6822b430b346248c2a40af/.circleci/config.yml#L88-L101

https://github.com/react-native-camera/react-native-camera/blob/42388be530f4a791ff6822b430b346248c2a40af/.circleci/config.yml#L62-L68

https://github.com/react-native-camera/react-native-camera/blob/42388be530f4a791ff6822b430b346248c2a40af/package.json#L80

https://github.com/react-native-camera/react-native-camera/blob/42388be530f4a791ff6822b430b346248c2a40af/package.json#L83-L105

**Comment by moaazsidat** [comment]
@renatobenks thanks for the links, definitely helps, considering just using Github Actions to prevent introducing another product to manage CI/release if possible, and keep the project contained on Github. 

seems like there's an action available to do just this which might help accomplish this
https://github.com/marketplace/actions/npm-publish

**Comment by moaazsidat** [comment]
Fixed, have updated the contribution guide to note how to follow semantic-release's commit convention to release: https://github.com/moaazsidat/react-native-qrcode-scanner/blob/master/CONTRIBUTION.md#formatting-for-commit-messages-for-merge-commits

Any feedback or improvements appreciated
