### ISSUE TITLE
Get the code?

### ISSUE THREAD

**Issue by nachovg** [moaazsidat/react-native-qrcode-scanner#31]
How can I get the code after read it? 
Thanks!

**Comment by moaazsidat** [comment]
@nachovg sorry not sure what you mean, you can always clone the repo to get the source code. 
Let me know if that answers your question, or if you have further questions.

**Comment by nachovg** [comment]
Sorry I didn't know how to get the Text when I scanned the code, but I just did it with e.data, thanks!
