### ISSUE TITLE
react-native-permissions: NativeModule.RNPermissions is null

### ISSUE THREAD

**Issue by michael0793** [moaazsidat/react-native-qrcode-scanner#314]
react-native-permissions: NativeModule.RNPermissions is null error

im working with android version but i get this error when i emulate using expo.

thanks

**Comment by mkdesilva** [comment]
I have mocked react-native-permissions in my own jestSetupFile.

I'm getting this error when running tests with jest.

**Comment by EvanErickson** [comment]
I'm getting this error too when I try to run. I think it has a problem with the podspec file.

**Comment by SudoPlz** [comment]
Just add

`jest.mock('react-native-qrcode-scanner', () => jest.fn());`

before your failing import (within your jest test).

**Comment by renatobenks** [comment]
that problem is actually because `react-native-permissions` is not compatible with expo as expo already has their own way to manage permissions by himself natively. For tests, the suggestion above works.

So, I'm closing this.
