### ISSUE TITLE
Why are some QR codes not recognized?

### ISSUE THREAD

**Issue by yurui-viatick** [moaazsidat/react-native-qrcode-scanner#320]
when scan this QR code, recognition is slow or even unrecognizable.

### Build details?

```javascript
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-camera": "^3.43.0",
"react-native-qrcode-scanner": "^1.5.3",
"react-native-permissions": "^3.0.1",
```

please help, I’m curious why scanning this QR code will not recognize it. Many other QR codes are recognized normally.

**Comment by yurui-viatick** [comment]
<img width="325" alt="QQ20210308-110054@2x" src="https://user-images.githubusercontent.com/62984643/110268979-9fd63080-7ffd-11eb-8b0a-ea87c86cb7e2.png">

**Comment by Pankti16** [comment]
It is scanning, I got result in Android, not sure of iOS
{"bounds":{"width":960,"height":720,"origin":[{"y":"460.6","x":"643.5"},{"y":"459.0","x":"413.0"},{"y":"222.44","x":"417.5"}]},"type":"QR_CODE","rawData":"10398de7f02195d000ec11ec11","data":"39792777010158","target":627}

<QRCodeScanner
           showMarker={false}
           onRead={e => onSuccess(e)}
           topViewStyle={{height: 0}}
           bottomViewStyle={{height: 0}}
           reactivate={true}
  />
  
  My onSuccess method is
  const onSuccess = (e) => {
        console.log("type: " + e.type + ", Scan Result: " +JSON.stringify(e))
   }
    
    "react-native-qrcode-scanner": "^1.5.4",  <- I am using this version
