### ISSUE TITLE
I cannot use react navigator in the onRead function

### ISSUE THREAD

**Issue by manan2501** [moaazsidat/react-native-qrcode-scanner#325]
### What's happening?
I am trying to navigate the user to a different screen when onRead is successful. But throws an error saying `TypeError: undefined is not an object (evaluating 'navigation.navigate')`

### How can it be reproduced?
Try to use react-navigation in the function of onRead to reproduce this error.

### Build details?
I am using the latest version of react-native-qrcode-scanner on a physical device running android.

### My code
```
import React from 'react';
import QRCodeScanner from 'react-native-qrcode-scanner';
import {RNCamera} from 'react-native-camera';
import {Text, View} from 'react-native';
import {globalStyles} from '../styles/global';
import {useDispatch} from 'react-redux';
import {startUsing} from '../redux/actions/deskActions';

const Start = ({navigation}) => {
  const dispatch = useDispatch();
  const onSuccess = e => {
    // dispatch(startUsing(e.data));
    console.log(e.data);
    navigation.navigate('Home');
    scanner.reactivate();
  };

  return (
    <View style={globalStyles.container}>
      <View style={{...globalStyles.center, marginVertical: 50}}>
        <Text style={{...globalStyles.titleText, marginBottom: 20}}>
          Scan the QR Code to start session
        </Text>
        <QRCodeScanner
          reactivate={true}
          reactivateTimeout={2000}
          showMarker={true}
          ref={node => {
            scanner = node;
          }}
          onRead={onSuccess}
          flashMode={RNCamera.Constants.FlashMode.auto}
          cameraStyle={{width: '80%', marginHorizontal: 20, height: '100%'}}
        />
      </View>
    </View>
  );
};

export default Start;
```

**Comment by hansderly** [comment]
Technically this should work if your Start Screen is defined on the same navigation container with your Home Screen!

const AppNavigator = () => {

  const Stack = createStackNavigator();

  return (
    <Stack.Navigator>
      <Stack.Screen
        name={'Home'}
        component={HomeScreen}
        options={{ headerShown: false }}
      />
      <Stack.Screen
        name={'Start'}
        component={ScanScreen}
        options={{ headerShown: false }}
      />
    </Stack.Navigator>
  );
}; 

you should have a configuration like that if you want to navigate to your Home screen

By the way if you have nested navigation, and you are using react navigation v5, you should do it like that navigation.navigate('Name of your navigation ', {screen : 'Home'})
Hope that help you!

**Comment by manan2501** [comment]
This is what my navigation container looks like

```
import React from 'react';
import {createStackNavigator} from '@react-navigation/stack';
import {NavigationContainer} from '@react-navigation/native';
import Home from '../screens/Home';
import Stop from '../screens/Stop';
import Start from '../screens/Start';

const Stack = createStackNavigator();

const AuthStack = () => {
  return (
      <Stack.Navigator
        screenOptions={{
          headerShown: false,
        }}>
        <Stack.Screen name="Home" component={Home} />
        <Stack.Screen name="Stop" component={Stop} />
        <Stack.Screen name="Start" component={Start} />
      </Stack.Navigator>
  );
};

export default AuthStack;
```

**Comment by hansderly** [comment]
I forgot to mention that you should add an arrow function to your onPress event
It should look like onPress = { () => onSucces() }
I reproduce that and it works perfectly! Try to add the arrow function on your OnPress event and let me know if it works!

**Comment by manan2501** [comment]
> I forgot to mention that you should add an arrow function to your onPress event
> It should look like onRead = { () => onSucces() }
> I reproduce that and it works perfectly! Try to add the arrow function on your onRead event and let me know if it works!

I tried this but this doesn't work too.

**Comment by hansderly** [comment]
if you're user react navigation v5 you can try using hook

`
...
import { useNavigation } from '@react-navigation/native';

const navigation = useNavigation()
const Start = () => {
  const dispatch = useDispatch();
  const onSuccess = e => {
    // dispatch(startUsing(e.data));
    console.log(e.data);
    navigation.navigate('Home');
    scanner.reactivate();
  };
...
`

**Comment by manan2501** [comment]
> if you're using react-navigation v5 you can try using hook

Yay! This is working as expected. Thanks a lot for helping. 😄

**Comment by hansderly** [comment]
Glad that help you!
Happy Coding @manan2501 !
