### ISSUE TITLE
Camera not authorized + iOS 14

### ISSUE THREAD

**Issue by huynhbinh06** [moaazsidat/react-native-qrcode-scanner#330]
Hi guys,
RN 0.63 + iOS 14
I used qr scanner but camera not authorized
I have react-native-camera, react-native-qrcode-scanner and permission in Xcode
![Simulator Screen Shot - iPhone 11 - 2021-05-05 at 13 55 44](https://user-images.githubusercontent.com/56378921/117106203-a8eb4000-ada9-11eb-8f38-b5b272dd0e0a.png)
Anybody can help me? pls

**Comment by junioroga** [comment]
Same problem here! Not requesting permission for camera.

**Comment by huynhbinh06** [comment]
I have solutions, thanks

**Comment by vinaygoyal20** [comment]
https://github.com/moaazsidat/react-native-qrcode-scanner/issues/237

Need to install  react-native-permissions
and  in pod file
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

**Comment by aravicubet** [comment]
> #237
> 
> Need to install react-native-permissions
> and in pod file
> pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

done both but still shows the same error on ios

**Comment by aravicubet** [comment]
@huynhbinh06 How did you fixed it?

**Comment by huynhbinh6** [comment]
> @huynhbinh06 How did you fixed it?

Hi, instead of we write this line in Podfile pod 'Permission-Camera', :path => "#{permissions_path}/Camera", replace pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
I don't understand why Podfile need " .podspec ", you can try this. Thanks

**Comment by aravicubet** [comment]
@huynhbinh06 
Got this error when updated the podfile:
`[!] No podspec found for `Permission-Camera` in `../node_modules/react-native-permissions/ios/Camera.podspec``

**Comment by huynhbinh6** [comment]
> @huynhbinh06
> Got this error when updated the podfile:
> `[!] No podspec found for `Permission-Camera`in`../node_modules/react-native-permissions/ios/Camera.podspec``

Did you have teamviewer?

**Comment by huynhbinh6** [comment]
> @huynhbinh06
> Got this error when updated the podfile:
> `[!] No podspec found for `Permission-Camera`in`../node_modules/react-native-permissions/ios/Camera.podspec``

please, add my skype, I will help you in 1 or 2hours live:.cid.a12a936b36a536b5

**Comment by thekundankamal** [comment]
HI All,

Have you found any working solutions.

**Comment by renatobenks** [comment]
it's probably something related to react-native-permissions, so please take a look there instead

**Comment by thekundankamal** [comment]
Yes, I got the solution..

**Comment by Aarush-wadhia** [comment]
@thekundankamal what's the solution? I am still struggling with the same

**Comment by thekundankamal** [comment]
@Aarush-wadhia 

Add this line  in pod file...
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

And then update the pod it will work.

**Comment by Aarush-wadhia** [comment]
@thekundankamal Hey buddy I tried this solution but it was showing the same error. Though I found the solution which was to check the permission since my colleague didn't make a proper code base I tweak it a lil bit and it is working as it should be. Thank you for your response

**Comment by amitbravo** [comment]
@Aarush-wadhia Please share your solution.
