### ISSUE TITLE
undefined is not an object(evaluating 'CameraManager.Aspect')

### ISSUE THREAD

**Issue by khunghang16** [moaazsidat/react-native-qrcode-scanner#34]

**Comment by moaazsidat** [comment]
@khunghang16 please add more details to your issue when filing one. 

This may help: https://github.com/lwansbrough/react-native-camera/issues/220
Generally points towards linking the npm module properly. 

Going to close this, please reopen if the issue persists.

**Comment by JimmyMow** [comment]
I am seeing this error after following the README. I noticed the react-native-camera dependency is 0.10.0 but their README states:

if on react-native < 0.40: npm i react-native-camera@0.4
if on react-native >= 0.40 npm i react-native-camera@0.6

Could this be an issue? I've rebooted. Linked and unlinked. Uninstalled and installed. No luck.

(react-native 0.50.3)

**Comment by WinterHuang3** [comment]
upgrade react-native-camera

**Comment by EsdrasEtrenne** [comment]
be sure to pod install after react-native link if you have cocoa pods
