### ISSUE TITLE
Turn on/off flash on custom button in top content of screen

### ISSUE THREAD

**Issue by prox2** [moaazsidat/react-native-qrcode-scanner#341]
Turn on/off flash based on custom button in the screen 
### What's happening?
it is actually a question, i have added custom button on top content of the screen and i want to be able to turn on/off the flash based on it

**Comment by Deodes** [comment]
@prox2 you can use state inside your component which tells you is flash on/off. By pressing button just switch state.

**Comment by prox2** [comment]
@Deodes  Thanks
