### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Amurmurmur** [moaazsidat/react-native-qrcode-scanner#35]
The app will crash if permissions are not give to the app.

My idea is to introduce:
```
  componentWillMount () {
    if (Platform.OS === 'ios') {
      Camera.checkVideoAuthorizationStatus().then(isAuthorised => {
        this.setState({ isAuthorised })
      })
    }
  }
```
Hope it helps.

**Comment by moaazsidat** [comment]
@Amurmurmur good idea, I like it, would you be able to create a PR for this! Thanks!

**Comment by Amurmurmur** [comment]
@moaazsidat Sweet just did it. On top of that added an empty component prop if no permissions given. Check it out #36

**Comment by ManigandanRaamanathan** [comment]
@moaazsidat for android how to check if the permission was accepted or denied? If denied then I would like perform other functions like closing the screen..."
