### ISSUE TITLE
Camera is active when  i navigate to another screen.

### ISSUE THREAD

**Issue by fiorelosLaconics** [moaazsidat/react-native-qrcode-scanner#366]
i am not sure if this is an issue or maybe i need to at some other settings but in ios whenever i change screens i get a signal that the camera is still active. any idea how i can fix this is this a issue others have faced?

**Comment by ZaharGusyatin** [comment]
hello, have you found fix about this bug?

**Comment by frabanca** [comment]
Hi @fiorelosLaconics , have you tried this solution? I've just tried and worked form me. 

[https://github.com/moaazsidat/react-native-qrcode-scanner/issues/136](https://github.com/moaazsidat/react-native-qrcode-scanner/issues/136)

**Comment by sangayt1997** [comment]
@fiorelosLaconics, did you made the reactivate={true}? for me this was the issues. when i made it reactivate={false} it worked.

**Comment by fpiantoni** [comment]
@fiorelosLaconics did you solved this?? 
I am having the same issue. Without the reactivate is still happening
