### ISSUE TITLE
Unable to scan text content qr code

### ISSUE THREAD

**Issue by LeoLaiFookSiang** [moaazsidat/react-native-qrcode-scanner#37]
Hi, I am not able to scan the QR Code with text content, it looks like only able to scare QR Code with HTTP link content, please help

**Comment by brandoncorbin** [comment]
Did you happen to figure out the issue? I'm running into this trying to store 300 bytes in the code, and it simply won't read. But with something short and sweet like a URL - it reads fine.

**Comment by LeoLaiFookSiang** [comment]
No I still unable to solve it. I use some encryption method to encrypt the information that I want to show then only make it to QR Code

**Comment by ObjectPlayer** [comment]
Hello, I am also facing this issue. Anyone have solution for it ??
