### ISSUE TITLE
Can't Update permission dialog message for IOS devices

### ISSUE THREAD

**Issue by ronakbuoyancy** [moaazsidat/react-native-qrcode-scanner#378]
My Code is
<QRCodeScanner
          onRead={(e) => onSuccess(e)}
          showMarker={true}
          markerStyle={{ borderColor: '#3a82cf' }}
          permissionDialogMessage={"Camera access is required to scan the QR code"}
          cameraContainerStyle={{ paddingTop: wp('20%') }}
        /
![IMG_4149 2](https://user-images.githubusercontent.com/102415580/167150544-3d603954-cf46-4b28-b24f-b3b4552a6cbc.PNG)
>

**Comment by AlfonsoRamat** [comment]
I think you can change this on info.plist where you set cammera permissions. permissionDialogMessage is for android only as said in the docs.
