### ISSUE TITLE
Android: undefined is not an object (evaluating styles.notAuthorizedView)

### ISSUE THREAD

**Issue by joncursi** [moaazsidat/react-native-qrcode-scanner#38]
I get a redbox error on Android when the app starts on latest version:

```
 undefined is not an object (evaluating styles.notAuthorizedView)
```

**Comment by GregorHorvatH** [comment]
i got this error too

**Comment by alekshs** [comment]
I am also getting 

> Cannot read property 'notAuthorizedView' of undefined

 when running this in xcode.

The styles constant is unreachable for some reason.
I also noticed that there is no import for the <Text> component.

**Comment by rochapablo** [comment]
+1

**Comment by moaazsidat** [comment]
hey all, apologies for the trouble, this got introduced in 0.0.21, things should be stable if you revert to 0.0.20, working on fix.

**Comment by moaazsidat** [comment]
Pushed a fix in [v0.0.22](https://www.npmjs.com/package/react-native-qrcode-scanner), please let me know if you run into further issues.

**Comment by PatrikTes** [comment]
0.0.22 is working

**Comment by joncursi** [comment]
LGTM 👍
