### ISSUE TITLE
How to deal with IOS and Android permissions using expo?

### ISSUE THREAD

**Issue by IamNotHuman** [moaazsidat/react-native-qrcode-scanner#39]
I'm developing on expo and what it does it gets rid of the android and ios folders and creates its own folders. So where can I find the "AndroidManifest.xml" and "Info.plist" or something equivalent for expo.

**Comment by moaazsidat** [comment]
@IamNotHuman would it be better to use the BarCodeScanner component that expo provides? does this help: https://snack.expo.io/HyiTlAn0e

**Comment by moaazsidat** [comment]
Going to close this since there wasn't any followup, please feel free to reopen if you still have questions. Cheers!
