### ISSUE TITLE
repeat scan

### ISSUE THREAD

**Issue by sam9010** [moaazsidat/react-native-qrcode-scanner#401]
I want to repeat scan and save barcodes
I mean when scan a barcode and go to function onRead , I can to read another scan on this time, how?
my code
`import React, { useState} from 'react';

import {StyleSheet, View, TouchableOpacity, Text} from 'react-native';

import QRCodeScanner from 'react-native-qrcode-scanner';
import {RNCamera} from 'react-native-camera';

const Scanner = ({navigation}) => {
  const [isFlashOn, setIsFlashOn] = useState(false);
 
  const onSuccess = e => {
    console.error(e.data);
  };

  const onPress = () => {};
  const onFlash = () => {
    setIsFlashOn(true);
  };
  return (
    <QRCodeScanner
      onRead={onSuccess}
      reactivate
      flashMode={
        isFlashOn
          ? RNCamera.Constants.FlashMode.torch
          : RNCamera.Constants.FlashMode.off
      }
      topContent={
        <View style={{flex: 1}}>
          <Text style={styles.centerText}>
             <Text style={styles.textBold}>scan</Text> 
          </Text>
       
        </View>
      }
      bottomContent={
        <TouchableOpacity
          onPress={() => onPress}
          style={styles.buttonTouchable}>
          <Text style={styles.buttonText}>close</Text>
        </TouchableOpacity>
      }
    />
  );
};

const styles = StyleSheet.create({
  centerText: {
    flex: 0.3,
    fontSize: 18,
    padding: 32,
    color: '#777',
  },
  textBold: {
    fontWeight: '500',
    color: '#000',
  },
  buttonText: {
    fontSize: 21,
    color: 'rgb(0,122,255)',
  },
  buttonTouchable1: {},
  buttonTouchable: {
    padding: 16,
  },
});

export default Scanner;
`

**Comment by trongtan** [comment]
You can. see this property: 
```reactivate
propType: bool default: false

When set to false, when a QR code is scanned, the QRCodeScanner will not scan another code until it is re-rendered. When set to true this will reactivate the scanning ability of the component.```

Follow this docs, it will help repeat the scan: https://enappd.com/blog/react-native-qr-code-scanning-using-react-native-camera/117/
