### ISSUE TITLE
 react-native-qrcode-scanner cannot read property oneOftype undefined 

### ISSUE THREAD

**Issue by adirzoari** [moaazsidat/react-native-qrcode-scanner#41]
I'm using react-native v0.49 and i have error when i run qrcode scanner.

>  cannot read property oneOftype undefined
```
import React, { Component } from 'react';
import {
    View,
    Text,
    TouchableOpacity,
    Linking,
    StyleSheet,
} from 'react-native';
import { style } from './style';
import { globalStyle } from '../../../assets/styles/globalStyle';

// redux
import { connect } from 'react-redux';
import * as actions from '../../../actions';


//third party library
import QRCodeScanner from 'react-native-qrcode-scanner';


class ScanPage extends Component {
    constructor(props) {
        super(props);
        this.state = {
            barcodeText: ''
        }

    }
    onSuccess(e) {
        this.setState({ barcodeText: e.data });
        console.log(e);
    }

    render() {
        const { } = style;


        return (
            <QRCodeScanner
                onRead={this.onSuccess.bind(this)}
                topContent={(
                    <Text style={styles.centerText}>
                        Go to <Text style={styles.textBold}>wikipedia.org/wiki/QR_code</Text> on your computer and scan the QR code.
          </Text>
                )}
                bottomContent={(
                    <TouchableOpacity style={styles.buttonTouchable}>
                        <Text style={styles.buttonText}>OK. Got it!</Text>
                    </TouchableOpacity>
                )}
            />
        );
    }
}

const mapStateToProps = () => {

}
const styles = StyleSheet.create({
    centerText: {
      flex: 1,
      fontSize: 18,
      padding: 32,
      color: '#777',
    },

    textBold: {
      fontWeight: '500',
      color: '#000',
    },

    buttonText: {
      fontSize: 21,
      color: 'rgb(0,122,255)',
    },

    buttonTouchable: {
      padding: 16,
    },
  });

export default connect(null, actions)(ScanPage);
```

I checked into the node_modules the react-native-qcode-scanner folder into examples and I did exaclty the example. in addition in index.js of this folder of the plugin I see the oneOfType property but I don't see any wrong from my side. t

**Comment by moaazsidat** [comment]
Would you be able to add the complete error message/possibly also a screenshot of the error, thanks!

**Comment by adirzoari** [comment]
![screen shot 2017-10-30 at 13 08 21 2](https://user-images.githubusercontent.com/20258998/32167999-823f06c8-bd73-11e7-894c-a73b6d7c1d12.png)

**Comment by moaazsidat** [comment]
@adirzoari when did you add `react-native-qrcode-scanner` to the project? 
a change was recently introduced to use the `prop-types` standalone package instead of using it from within the `react` module which is going to be deprecated. My guess is that for some reason, `prop-types` wasn't installed correctly (since that's the only place the package uses `oneOfType`, can you try running `yarn` or `npm install` again to make sure `prop-types` is currently installed.

Let me know how that goes.

**Comment by adirzoari** [comment]
I installed it today actually. and I tried to install again. when i delete the plugin\import to qr scanner, the app works fine. so the issue is this plugin.

**Comment by moaazsidat** [comment]
Going to have to look into this further, may be able to get to this tonight or tomorrow.

**Comment by adirzoari** [comment]
thank you for your time.

**Comment by adirzoari** [comment]
hey @moaazsidat, I'm sorry but it's was my fault.
I had react-native-camera version 0.6.0 and when i deleted it and install again react-native-camera the current version is 0.10.0 and it solve my problem. so it's not issue of react-native-qrcode-scanner. sorry, thank you for your time.

**Comment by moaazsidat** [comment]
No worries, glad the issue was resolved!
