### ISSUE TITLE
help, when onRead() ,black screen and exit..

### ISSUE THREAD

**Issue by kidolee** [moaazsidat/react-native-qrcode-scanner#43]
```
//this is scanPager

 import React, { Component } from 'react';

 import {
   AppRegistry,
   StyleSheet,
   NavigatorIOS,
   Dimensions,
   View,
   Text,
   TouchableHighlight
 } from 'react-native';
import Icon from 'react-native-vector-icons/FontAwesome';
 import QRCodeScanner from 'react-native-qrcode-scanner';

 export default class WarehouseOutScan extends Component {
   static navigationOptions = ({navigation,screenProps}) => ({
       headerLeft:(
         <View style={{flexDirection: 'row', justifyContent: 'center', alignItems: 'center', width: 60,height: 40}}>
           <TouchableHighlight underlayColor='#EEEEF4' disabled={thes.state.disabled} onPress={() => {
             const { goBack } = navigation;
             goBack();
           }}>
             <View style={{marginRight: 20, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', width: 60, height: 40}}>
               <Icon name='angle-left' size={35} color='black' />
             </View>
           </TouchableHighlight>
         </View>
       ),
   });

   constructor(props) {
     super(props);
     this.onSuccess = this.onSuccess.bind(this);
   }

   onSuccess(e) {
     const { goBack } = this.props.navigation;
     this.props.data.navigation.state.params.callback(e.data);
     goBack();
   }

   render() {
     return (
        <QRCodeScanner
          onRead={()=>this.onSuccess(e)}
          fadeIn={false}
          cameraStyle={{height: DeviceHeight}}
          showMarker={true}
        />
     )
   }
 }

 const styles = StyleSheet.create({
   zeroContainer: {
     height: 0,
     flex: 0,
   },

   cameraContainer: {
     height: Dimensions.get('window').height,
   },
 });

AppRegistry.registerComponent('demo', () => WarehouseOutScan);
```

//this is usePage

          <View style={[styles.valueCell,{borderWidth: 1, borderStyle: 'dashed', borderColor: 'black', marginLeft: 20, width:((DeviceWidth-30)*(1/5)), height:(DeviceHeight/16)}]}>
            <TouchableHighlight underlayColor='gray' disabled={thes.state.disabled} onPress={() => {
              const { navigate } = this.props.navigation;
              navigate('WarehouseOutScan', {
                callback: (trackingNumber)=>{
                  this.setState({trackingNumber: trackingNumber});
                }
              });
            }}>
              <View style={[styles.valueCell,{width:((DeviceWidth-30)*(1/5)), height:(DeviceHeight/16)}]}>
                <Image source={Scanner} resizeMode='stretch' style={{width: 30, height: 30}}/>
              </View>
            </TouchableHighlight>
          </View>

========================================================================
   onSuccess(e) {
     const { goBack } = this.props.navigation;
     this.props.data.navigation.state.params.callback(e.data);
     goBack();
   }

question:  
what's the structure of the return value (e);

**Comment by moaazsidat** [comment]
Structure of `event` in the callback: https://github.com/lwansbrough/react-native-camera#onbarcoderead

**Comment by moaazsidat** [comment]
Closing this, please feel free to reopen if still unresolved.
