### ISSUE TITLE
Access a feature from camera module itself

### ISSUE THREAD

**Issue by brunomazzardo** [moaazsidat/react-native-qrcode-scanner#47]
Can I from your module have access to features like turning on flash from the camera module you used to implement this scanner?

**Comment by moaazsidat** [comment]
@brunomazzardo not currently, but this module uses the [react-native-camera](https://github.com/lwansbrough/react-native-camera) module which does allow passing a proptype to control the flash, will accept PRs adding that functionality of passing the prop down to `react-native-camera`
