### ISSUE TITLE
.reactivate is not a function

### ISSUE THREAD

**Issue by acrocat** [moaazsidat/react-native-qrcode-scanner#50]
I'm trying to reactivate the camera after the user acknowledges that their last scan failed. 
```
Alert.alert(
	"Didn't Work",
	"We couldn't find an event for this code.",
	[
		{
			text: "OK",
			onPress: () => {
				setTimeout(() => {
					qrCodeScanner.reactivate();
				} , 1000)
			}
		}
	]
);
```

In debugging I can see that `qrCodeScanner` is correctly set as my reference, but this call errors and tells me that reactivate is not a function.

**Comment by brunomazzardo** [comment]
Can you send your QRCodeScanner tag?

**Comment by moaazsidat** [comment]
@acrocat is this issue still unresolved? if so, please reopen, and also link to/paste the rest of the code to debug, thanks!
