### ISSUE TITLE
[Android] Attempted to redefine property `cameraType`

### ISSUE THREAD

**Issue by joncursi** [moaazsidat/react-native-qrcode-scanner#52]
Android is broken on the latest release due to this error. Looks like this was fixed in https://github.com/moaazsidat/react-native-qrcode-scanner/pull/49

Can we get a new version deployed to NPM?

**Comment by moaazsidat** [comment]
my bad, published 0.0.25

**Comment by diamedi** [comment]
Hey guys,

I got rid of the error when I comment out my script with the scanner and hot reload it back into while running the app.

Works fine for me
