### ISSUE TITLE
Camera not authorized

### ISSUE THREAD

**Issue by rahulmenon87** [moaazsidat/react-native-qrcode-scanner#54]
I am getting Camera not authorized error on android 5.1 device. Camera loads well on emulator with android 6.

**Comment by moaazsidat** [comment]
@rahulmenon87 you may need to reauthorize the app to use the camera, we recently added this: https://github.com/moaazsidat/react-native-qrcode-scanner/blob/master/index.js#L88-L95

**Comment by moaazsidat** [comment]
should be fixed [here](https://github.com/moaazsidat/react-native-qrcode-scanner/pull/55)

**Comment by afilp** [comment]
@moaazsidat Hello, in Android 5.1 I also get this "camera not authorized", despite I have the 0.0.28 version.

I am not sure what you mean to "reauthorize" the app. The app shows "take pictures and videos" in the PERMISSIONS properties at "App Info" settings.

Can you please clarify what we need to do? Thanks!

**Comment by moaazsidat** [comment]
I've pushed a temp fix for this in 0.0.29, please let me know if it fixes the issue

**Comment by afilp** [comment]
@moaazsidat First test, seems to be working! Thanks.

Please also read my comment at #61

**Comment by 100rabhchauhan** [comment]
> @rahulmenon87 you may need to reauthorize the app to use the camera, we recently added this: https://github.com/moaazsidat/react-native-qrcode-scanner/blob/master/index.js#L88-L95

how about if I want to style not Authorized view in android?

**Comment by renatobenks** [comment]
what you exactly wanna mean with "not Authorized view"? this is just related to the permissions authorization cases
