### ISSUE TITLE
May I use this on creat react native?

### ISSUE THREAD

**Issue by Dubroy** [moaazsidat/react-native-qrcode-scanner#57]

**Comment by hllhui** [comment]
creat react native had own qrcode-scanner ,very easy to use, 'expo camera'

**Comment by moaazsidat** [comment]
yep, what @hllhui said. 
you can find an example of that here: https://snack.expo.io/HyiTlAn0e

this module won't work with create-react-native-app without ejecting it because of how it requires you to link the dependent react-camera module.
