### ISSUE TITLE
Looking for an Android developer as a core contributor

### ISSUE THREAD

**Issue by moaazsidat** [moaazsidat/react-native-qrcode-scanner#59]
Hey folks, looking for Android developer to help tackle Android specific issues that come along in this project. If you're interested in helping out, leave a comment below. Thanks and cheers!

**Comment by moaazsidat** [comment]
@Taym95 sweet, have a couple of issues open that are labelled 'android', feel free to take on some of those, and submit PRs for any, thanks!

Can add you to contributors once we have a couple of PRs in, let me know if that sounds good, cheers!

**Comment by Taym95** [comment]
Yeah that sounds good!
