### ISSUE TITLE
Never requested camera permission

### ISSUE THREAD

**Issue by felgarte** [moaazsidat/react-native-qrcode-scanner#61]
I followed all the steps to install the lib and all seems works fine, but when I install the app in a real device, I got never see the camera permission request.

```
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.VIBRATE" />
```

I see "Camera not authorized" in the view.

Any help?

**Comment by hllhui** [comment]
i also met this problem, and i change the index.js line 109:
'this.setState({ isAuthorized: granted ===  PermissionsAndroid.RESULTS.GRANTED, isAuthorizationChecked: true })'
to
'this.setState({ isAuthorized: granted, isAuthorizationChecked: true })'
then not show 'Camera not authorized' any more

**Comment by rizwanahmed19** [comment]
I'm facing the same issue.

**Comment by moaazsidat** [comment]
accepting PRs to fix this, thanks!

**Comment by moaazsidat** [comment]
I've pushed a temp fix for this in 0.0.29, please let me know if it fixes the issue

**Comment by afilp** [comment]
@moaazsidat First test, seems to be working! Thanks.

(since this is a temp solution, could it break in some cases?)

**Comment by JAISWAL007** [comment]
Did this issue is solve ? I'm facing same problem..
