### ISSUE TITLE
QR scanner not showing Android 5 or under

### ISSUE THREAD

**Issue by williameot** [moaazsidat/react-native-qrcode-scanner#63]
I followed the instructions from this link:
https://github.com/moaazsidat/react-native-qrcode-scanner/issues/61
"Camera not authorize" message is gone but the screen is blank.  
I turn the camera on and use the device built-in camera app to confirm that the camera works. 
Then I restarted the android device, turn on the camera again and try the qr scanner but still see the white screen.
Can this be fixed?
Android 4.2.2, 4.2, 5.0 failed

**Comment by moaazsidat** [comment]
I've pushed a temp fix for this in 0.0.29, please let me know if it fixes the issue

**Comment by williameot** [comment]
Looks like it is fixed.  Thanks.
