### ISSUE TITLE
Showing blank white screen on android

### ISSUE THREAD

**Issue by chixpc123** [moaazsidat/react-native-qrcode-scanner#73]
Hello @moaazsidat ,

I'm having similar issue as declare [here](https://github.com/moaazsidat/react-native-qrcode-scanner/issues/72)

### What's happening?
I integrate react-native-camera and also tried given example on react-native-camera page which you can show by [clicking here](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md).
It's working fine for me.
after that i integrate react-native-qrcode-scanner & it showing me totally blank screen.

### How can it be reproduced?
after integrate react-native-qrcode-scanner it showing me blank screen

### Build details?
I'm working on..
`"react": "^16.3.0-alpha.1",`
 `"react-native": "0.54.2",`
 `"react-native-camera": "git+https://git@github.com/react-native-community/react-native-camera",`
`"react-navigation": "^1.5.7"`

I'm using Android Nougat .
please check attached screen sort
![556877186307482995](https://user-images.githubusercontent.com/23215308/37592906-2e6727ce-2b96-11e8-86ac-0be189b54f5f.png)

**Comment by moaazsidat** [comment]
Thanks for filing this issue, this may be due to a new version of react-native-camera, going to investigate this further.

**Comment by moaazsidat** [comment]
we've just released [v1.0.0](https://www.npmjs.com/package/react-native-qrcode-scanner) with the new react-native-camera updates, can you try that and see if it works, please also take a look at the [migration guide](https://github.com/moaazsidat/react-native-qrcode-scanner/blob/master/migration.md).

**Comment by Bardolos** [comment]
I was having the same problem. I had updated react-native-qrcode-scanner to 1.0.0 and react-native-camera to 1.0.3. Project built fine but when I navigated to the scene the component didn't seem to be rendered. I could see the topView and the bottomView parts of it, but not the cameraView. 

So I solved the problem by explicitly setting the width and height in the cameraStyle prop. Check if your style has `position: 'absolute'` in it. Try removing that and setting width and height.

**Comment by kristerkari** [comment]
I have having the same issue as @chixpc123. There reason why the app was only showing a red line was that I was trying to run the ios example on Android.

Here's the android version which works just fine:
https://github.com/moaazsidat/react-native-qrcode-scanner/blob/master/examples/default.android.js

@moaazsidat What about adding both Android and iOS examples to the README to avoid confusion? I can provide a PR if you want.

**Comment by moaazsidat** [comment]
That sounds like a good idea, thanks @kristerkari!

**Comment by moaazsidat** [comment]
Seems like this is a styling/example issue which is resolved above, if it's still an issue, please feel free to reopen, thanks

**Comment by harrischelsea** [comment]
I solved problem. Try to remove other xml tags.

Try only this.
For example: 
```
<View>
 <QRCodeScanner .... />
</View>
```

**Comment by GaneshSaiKumar** [comment]
@moaazsidat  still facing this issue

**Comment by siliconavengers** [comment]
@moaazsidat i'm running the example app on a device (android 5.1). It's still facing the issue - a black screen.
