### ISSUE TITLE
Upgrade to latest version of react-native-camera and use RNCamera

### ISSUE THREAD

**Issue by sibelius** [moaazsidat/react-native-qrcode-scanner#74]

**Comment by moaazsidat** [comment]
thanks for bumping this, @sibelius, wondering if you'd be able to help out with the upgrade? thanks!

**Comment by alexgurr** [comment]
I'll take a stab at this.

**Comment by moaazsidat** [comment]
released in [v1.0.0](https://www.npmjs.com/package/react-native-qrcode-scanner)
@sibelius do you think this library would be a good fit for React Native Community? thanks!
