### ISSUE TITLE
Disable vibration when scanner is not active

### ISSUE THREAD

**Issue by mamodom** [moaazsidat/react-native-qrcode-scanner#8]
When `reactivate` is set to false, after the first scan, each time a qr code is  scanned, the phone vibrates, and the user might think they're actually scanning something.

**Comment by moaazsidat** [comment]
Just so that I'm understanding this correctly, you want the vibration to just be for the first scan, and not subsequent scans? If so, what's the reasoning behind that?

**Comment by mamodom** [comment]
Actually, what I think should happen is that if `reactivate` is false (which is the default value), when you scan a qr code and you happen to not re-render the `QRCodeScanner` component (let's say you show an alert message telling the user that the QR code he scanned didn't meet some expectations), unless the component is re-rendered or reactivated, if the camera stumbles upon a QR code, it shouldn't vibrate, because it's not scanning.

**Comment by mamodom** [comment]
Another thing which is slightly unrelated to this issue is that I didn't really understand how I could reactivate the `QRCodeScanner` without re-rendering it.

Let's take this scenario: 
- I open the app which tells me to scan a specific Qr code (the back of a book or something) to do a specific action with it.
- I derp out and scan some other Qr code.
- I see an alert telling me that I didn't scan a valid Qr code (for the specific action the app is for.)
- Until I press the hypothetical  "Ok" button in the hypothetical alert box, the `QRCodeScanner` which is behind the Alert shouldn't scan anything.

**Comment by moaazsidat** [comment]
Thanks for the elaboration, let me think about it, and play with it a bit later today and get back to you, thanks @mamodom!

**Comment by pckz** [comment]
I've been using router flux in my app, and when the QR Scanner code is actived, and you pushed a new Scene `Action.sceneName({qr: e.data})` the camera is still working in background, and when a QR is recognized still vibrating, but the actions when a QR code is detected not working (is fine that not work, but is not fine that keep working on background)
So I solved pushing the new scene with type:reset like `Action.sceneName({type: 'reset', qr: e.data})`

**Comment by skycsky** [comment]
agree with mamodom.
  _handleBarCodeRead(e) {

    if (!this.state.scanning) {
      Vibration.vibrate();
      this._setScanning(true);
      this.props.onRead(e)
      if (this.props.reactivate) {
        setTimeout(() => (this._setScanning(false)), this.props.reactivateTimeout);
      }
    }
    return;
  }

move       Vibration.vibrate();
into if condition will be good.

**Comment by moaazsidat** [comment]
Released in v0.0.12
