### ISSUE TITLE
Not getting prompted for camera access on iOS

### ISSUE THREAD

**Issue by ErikMejerHansen** [moaazsidat/react-native-qrcode-scanner#80]
It looks like the user is not getting prompted to allow access to the camera on iOS. 
### What's happening?
Using the `<QRCodeScanner>`-component but the user never sees the prompt asking for access to the camera. 
The `NSCameraUsageDescription` string has been added to `Info.plist`. 

Seems like `Permissions.request(CAMERA_PERMISSION)` returns "undetermined" causing the not authorized view to be show. 

Changing line 105 in `index.js` from ` Permissions.check(CAMERA_PERMISSION)` to ` Permissions.request(CAMERA_PERMISSION)` seems to resolve the issue. 

### How can it be reproduced?
Create component using <QRCodeScanner>

### Build details?

```react-native-qrcode-scanner@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/react-native-qrcode-scanner/-/react-native-qrcode-scanner-1.0.0.tgz#6c9994285373d5bc386f58401581acff3ee1b4b2"
  dependencies:
    prop-types "^15.5.10"
    react-native-permissions "^1.1.1"
```

**Comment by kristerkari** [comment]
I ran into the same issue when upgrading to newest `react-native-qrcode-scanner` version. 

This fix worked for me:

> Changing line 105 in index.js from Permissions.check(CAMERA_PERMISSION) to Permissions.request(CAMERA_PERMISSION) seems to resolve the issue.

**Comment by kristerkari** [comment]
I opened a PR #81.

**Comment by MikeGsus** [comment]
I've something similar:

When I try to use the component it shows a loader but never appears the camera.
The app has camera permissions. This trouble doesn't happen with Android, it's only with iOS

![88607632-4C20-4D57-8929-9CA145940989](https://user-images.githubusercontent.com/19364241/75295894-6915e980-57f1-11ea-9911-b4f7485f42da.png)
