### ISSUE TITLE
After linking 

### ISSUE THREAD

**Issue by markib** [moaazsidat/react-native-qrcode-scanner#92]
After  Linking camera and qr scanner
### What's happening?

Build file '\node_modules\react-native-camer
a\android\build.gradle' line: 4

* What went wrong:
A problem occurred evaluating project ':react-native-camera'.
> Could not find method google() for arguments [] on repository container.

**Comment by Rananjaya** [comment]
same problem here. any updates?

**Comment by vikumDheemantha** [comment]
I had the same issue, wasted more than 3 hours. Still couldn't figure out a way to resolve this. Any one know how to fix this?

**Comment by velvetrain** [comment]
yeah I had the same issue as well , it would be a huge help if someone could give a possible solution to fix this!!

**Comment by taboca** [comment]
This issue relates to the dependency project entitled "react-native-camera". The issue was also filed within that project: 

https://github.com/react-native-community/react-native-camera/issues/1530#issuecomment-385752864

**Comment by moaazsidat** [comment]
closing this as it seems like it was fixed, please reopen if still an issue
