### ISSUE TITLE
Show Marker doesn't work 

### ISSUE THREAD

**Issue by szejing547** [moaazsidat/react-native-qrcode-scanner#93]
### What's happening?

I've encountered of the "show marker" issue. I'm using the default marker.

### How can it be reproduced?

```
 return (
            <QRCodeScanner
                onRead={this.onSuccess.bind(this)}
                showMarker
            />
        );
```

### Build details?

It doesn't work for Android and iOS. And I'm using 
"react-native-camera": "^1.0.0",
"react-native-qrcode-scanner": "^1.0.1",

**Comment by tedwong** [comment]
u need to call `customMarker` to let the marker draw.

**Comment by moaazsidat** [comment]
@szejing547 going to close this since the above lacks details of the implementation, you need to set `showMarker` to `true` and pass an element to `customMarker` prop to render the marker. 

please reopen if the issue still persists.
