### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by markib** [moaazsidat/react-native-qrcode-scanner#96]
### What's happening?
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Check the render method of `QRCodeScanner`.

### Build details?

"prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-native": "0.55.3",
    "react-native-camera": "^0.5.1",
    "react-native-qrcode-scanner": "^1.0.1"

windows 8

**Comment by raulcostea77** [comment]
I have the same error...
"react": "^16.3.0-alpha.3",
"react-native": "^0.54.2"
"react-native-camera": "^0.10.0",
"react-native-qrcode-scanner": "^1.0.1",

**Comment by ybintian** [comment]
"react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-camera": "^1.1.4",
    "react-native-qrcode-scanner": "^1.0.1"

**Comment by moaazsidat** [comment]
please provide a link to a codebase/repo to reproduce this, going to close this for now, please feel free to reopen with further details

**Comment by matoxxx** [comment]
I've same error:

    "react": "16.4.1",
    "react-native": "0.56.0",
    "react-native-camera": "^1.2.0",
    "react-native-qrcode-scanner": "^1.0.1"

Link to my repository for reproduce: https://github.com/matoxxx/react-native-qrcode-scanner-error

**Comment by fallerd** [comment]
I was able to find this page which described a few solutions: https://github.com/facebook/react-native/issues/16332

I was able to solve this by changing this line:
`class ScanScreen extends Component {`
to this: 
`export default class ScanScreen extends Component {`
