### ISSUE TITLE
How to reactivate the camera after the user acknowledges that their last scan failed.

### ISSUE THREAD

**Issue by ghost** [moaazsidat/react-native-qrcode-scanner#99]
When i get error in scanning, i need to scan again but it is not allowing. How to reactivate the scanner

**Comment by brunomazzardo** [comment]
If you have a ref to the scan, call ref.reactivate() when you have the error, or you can call a function that does it, like the one below 


`_reactivate = throttle(() => {
    if (this.scanner)
      this.scanner.reactivate();
  }, 2000, {trailing: true, leading: false});
`
